# ============================================================
# Praat AudioTools - Fuzzy_Time_Recomposer.praat
# Author: Shai Cohen
# Affiliation: Department of Music, Bar-Ilan University, Israel
# Email: shai.cohen@biu.ac.il
# Version: 0.4.0 (2026) - Fuzzy rule-based time re-composition, audited Picture output
# License: MIT License
# Repository: https://github.com/ShaiCohen-ops/Praat-plugin_AudioTools
#
# Description:
#   Treats the selected Sound as malleable temporal material rather
#   than a fixed timeline. The script:
#     1. SEGMENTS the sound adaptively (energy onsets / grid / pitch
#        periods)
#     2. Measures per-segment acoustic descriptors and maps them onto
#        fuzzy sets mu_Transient, mu_Sustain, mu_Motion, mu_HF,
#        mu_Entropy, mu_Low, mu_Rise
#     3. Fires a rule base that yields, per segment, BOTH a continuous
#        time-warp factor (Sugeno-style defuzzification) and a
#        discrete gesture (preserve / dilate / compress / granulate /
#        retrograde / ostinato)
#     4. RE-ORDERS the segment vector (sequential / nearest-profile /
#        shuffle / retrograde / interleave)
#     5. Re-assembles with fuzzy crossfades whose length follows
#        mu_Sustain
#
# Honest scope notes (read before using):
#   - Feature thresholds are self-calibrating: every descriptor is
#     normalised across the segments of THIS file, so "high
#     transientness" is relative to the material, not an absolute dB
#     figure. Comparing two different files compares two different
#     scales.
#   - Time-warping uses Praat's PSOLA "Lengthen (overlap-add)",
#     clamped to 0.25x-3.0x per pass and chained for larger factors.
#     Segments shorter than 4/Pitch_floor seconds are left unwarped
#     (reported, not silently).
#   - Assembly writes grains into a pre-allocated buffer at
#     sample-aligned offsets. It does NOT use Concatenate, and is
#     therefore not exposed to the object-list-order trap that
#     Concatenate has in Praat.
#   - Analysis uses one cancellation-safe mono reference. Rendering preserves
#     every input channel: the same fuzzy decisions, grain order, micro-grain
#     permutation, and deterministic PSOLA seeds are applied independently to
#     each channel before re-combination. The analysis copy is level-normalized
#     only for descriptor stability; rendered audio is never normalized upward.
#     This avoids anti-phase cancellation
#     while acknowledging that Praat Lengthen (overlap-add) itself is mono-only.
#   - The re-composed timeline deliberately starts at 0 s because ordering and
#     duration are newly generated by the composition process.
#
# Changelog v0.4.0 (2026):
#   Visualization audit. Rendered audio is bit-identical to v0.3.1; the only
#   non-drawing change is that the rule loop now also RETAINS the runner-up
#   activation (same argmax, same warp, same gestures - verified by diffing
#   the full report against v0.3.1 on identical input).
#
#   Corrections:
#   - FIXED the Source panel, which did not show the source. It drew the
#     analysis object, which is level-normalised to 0.5 peak, on fixed +-1
#     axes, so every input looked equally loud and filled exactly half the
#     panel. It now draws an un-normalised display copy that follows the same
#     channel decision the analysis made (so segment boundaries still align).
#   - Source and Output now share one amplitude scale. Previously Source used
#     fixed +-1.18 and Output used peakFinal * 1.34, so the before/after
#     comparison carried no information.
#   - Segment boundaries were 0.45-wide lines in {0.78} grey on a {0.97}
#     background, i.e. invisible in a panel titled "segmentation". Now:
#     explicit boundaries up to 60 segments, alternating bands above that.
#   - The Output waveform is no longer blue. {0.25,0.50,0.82} was effectively
#     the "dilate" gesture colour, which broke the one-colour-one-meaning rule
#     the gesture palette depends on. It is now neutral dark grey.
#   - The gesture legend moved out of the decision map into its own band. It
#     had been consuming 0.46 * logSpan of reserved headroom inside the plot.
#     The artificial 1.35 minimum on logSpan is gone as well, replaced by an
#     absolute 0.60 floor, so a narrow warp range is neither squashed by
#     reserved space nor stretched into false drama.
#   - Warp reference labels (0.25x .. 8x) moved from inside the data area to
#     proper axis marks outside the box, where they can no longer land on top
#     of a segment marker.
#   - Segment stems and markers are now drawn in two passes, so a later
#     segment's stem cannot paint over an earlier segment's marker.
#   - Panels that share the source-time axis are pixel-aligned and the axis is
#     numbered rather than merely labelled; the identity reference in the
#     remapping panel is labelled as such, since the two axes have different
#     scales and it is therefore not a 45-degree diagonal.
#
#   Additions:
#   - New "Fuzzy memberships" panel: one row per fuzzy set (transient,
#     sustain, motion, HF, entropy, low, rise), one cell per segment, shade =
#     mu. The Picture output previously showed only the inference OUTPUT; the
#     inference INPUT, which is the point of the script, was absent. Greyscale
#     only, so colour keeps its single meaning.
#   - Segments are drawn as bars spanning segT0..segT1 instead of a dot at the
#     centre, so segment length is visible in a script about time.
#   - Decision confidence: the winning rule's margin over the runner-up is now
#     stored per segment. A confident decision is a filled marker, a close call
#     (margin < 25%) is a ring. The census is reported in the Info log and in
#     the Summary panel.
#   - Summary gained a gesture census line.
#
# Changelog v0.3.1 (2026):
#   - Rebuilt the Picture output around the actual transformation chain:
#     Source -> fuzzy decision map -> temporal remapping -> Output -> Summary.
#   - The decision map plots defuzzified warp on a log2 factor axis and
#     uses physical-mm markers whose colour has one meaning only: the
#     winning discrete gesture. Marker size adapts to segment count.
#   - Added dedicated visual headroom for titles/legends and removed the
#     overlapping membership labels seen in the previous Picture layout.
#   - Time-map lines retain gesture colour, with adaptive display thinning
#     only for very large grain counts; DSP, rule inference and rendering
#     are unchanged.
#
# Changelog v0.3 (2026):
#   - FIXED zero-crossing boundary snapping: an interior boundary is now
#     accepted only if it stays between BOTH neighbouring boundaries. Sparse
#     zero crossings can no longer move a boundary past the next segment and
#     create zero/negative-duration material.
#   - FIXED Random_seed=0 reproducibility. An unpredictable concrete seed is
#     now generated once, immediately re-used as the deterministic run seed,
#     and printed in the report; copying that seed reproduces the full run.
#   - PSOLA chain depth is now derived from Max_dilation / Max_compression
#     instead of being silently capped at four passes. Requests needing more
#     than eight chained overlap-add passes are rejected before rendering.
#   - Report now states the computed maximum PSOLA pass count.
#
# Changelog v0.2 (2026):
#   - Preserves arbitrary multichannel input instead of folding the output to mono.
#   - Added cancellation-safe analysis fold-down with loudest-channel fallback.
#   - Made output-order trajectories truly follow the re-composed order.
#   - Renamed misleading Fuzzy Markov / hysteresis labels to truthful terms.
#   - Removed unconditional DC subtraction and exposed attenuation-only Safety_peak.
#   - Added deterministic per-segment render seeds and robust Random_seed clamping.
#   - Updated visualization to the AudioTools house style, including panel text,
#     value annotations, subtitle metadata, and a two-line Summary.
#
# Changelog v0.1 (2026):
#   - Initial release, restyled to library conventions: house-style
#     header, no-colon form syntax, four-space indentation, and
#     paired outer+inner viewport panel layout for the visualisation.
#     No change to the analysis, rule base, or rendered audio.
#
# Citation:
#   Cohen, S. (2025). Praat AudioTools: An Offline Analysis-Resynthesis
#   Toolkit for Experimental Composition.
#   https://github.com/ShaiCohen-ops/Praat-plugin_AudioTools
#
# Category: Composition
# ============================================================

# ============================================================
# INPUT VALIDATION
# ============================================================

if numberOfSelected("Sound") <> 1
    exitScript: "Please select exactly one Sound object before running."
endif

src = selected("Sound")
srcName$ = selected$("Sound")

# ============================================================
# FORM
# ============================================================

form Fuzzy Time Re-Composer v0.4.0  (Fuzzy Rule-Based Time Recomposition)
    optionmenu Preset 1
        option Manual (use fields below)
        option Micro-shuffle (transient granulation)
        option Frozen resonance (harmonic dilation)
        option Directional mirroring (retrograde arches)
        option Poly-temporal interleave
        option Entropy injection (order to chaos)
    optionmenu Segment_mode 1
        option Adaptive onsets (energy delta)
        option Fixed grid
        option Pitch periods (PointProcess)
    positive Segment_length_ms 120
    positive Pitch_floor 75
    positive Pitch_ceiling 600
    real Fuzzy_sensitivity 0.5
    real Fragmentation 0.5
    real Dilation 0.5
    real Mirroring 0.3
    positive Max_dilation 4.0
    positive Max_compression 0.35
    optionmenu Reorder_mode 1
        option Sequential
        option Fuzzy nearest-profile chain
        option Shuffle
        option Retrograde order
        option Interleave (odd then even)
    optionmenu Trajectory 1
        option None
        option Order to chaos
        option Chaos to order
    integer Random_seed 20260808
    comment --- Output ---
    real Safety_peak 0.99
    comment (0 disables; otherwise attenuation only)
    boolean Draw_analysis 1
    boolean Play_result 1
endform

# Preset applies a whole bundle of settings at once; choosing a preset
# overrides the fields above. Fragmentation/Dilation/Mirroring are
# rule-bias weights (0 = off, 1 = strong), not probabilities. Fuzzy_sensitivity
# controls membership contrast around the neutral point 0.5, so it
# need not sum to 1. Random_seed: a fixed value reproduces a run
# exactly; leaving it as-is is already a fixed seed (change it, or see
# the Info log for the seed actually used).
#
# To keep the form on one screen, the grain/crossfade/output knobs
# below are fixed constants rather than form fields. Presets still
# override Micro_grain_ms/Fade_min_ms/Fade_max_ms internally; if you
# need to hand-tune them, edit the values just below.
onset_sensitivity = 1.0
micro_grain_ms = 22
fade_min_ms = 3
fade_max_ms = 60
crossfade_law = 1
crossfade_law$ = "Equal gain (raised cosine)"

# ============================================================
# PRESET LOGIC
# ============================================================

presetNote$ = "Manual settings used as entered."
if preset = 2
    segment_length_ms = 90
    fragmentation = 0.90
    dilation = 0.15
    mirroring = 0.10
    max_dilation = 1.6
    max_compression = 0.45
    reorder_mode = 1
    trajectory = 1
    micro_grain_ms = 16
    fade_min_ms = 2
    fade_max_ms = 25
    fuzzy_sensitivity = 0.65
    presetNote$ = "Micro-shuffle: transient-rich segments shatter into 16 ms grains."
elsif preset = 3
    segment_length_ms = 200
    fragmentation = 0.10
    dilation = 0.95
    mirroring = 0.10
    max_dilation = 8.0
    max_compression = 0.60
    reorder_mode = 1
    trajectory = 1
    micro_grain_ms = 30
    fade_min_ms = 10
    fade_max_ms = 180
    fuzzy_sensitivity = 0.60
    presetNote$ = "Frozen resonance: harmonic, pitch-static segments dilate up to 8x."
elsif preset = 4
    segment_length_ms = 160
    fragmentation = 0.20
    dilation = 0.35
    mirroring = 0.95
    max_dilation = 2.5
    max_compression = 0.50
    reorder_mode = 1
    trajectory = 1
    micro_grain_ms = 24
    fade_min_ms = 8
    fade_max_ms = 120
    fuzzy_sensitivity = 0.60
    presetNote$ = "Directional mirroring: rising-energy segments are favoured for retrograde arches."
elsif preset = 5
    segment_length_ms = 110
    fragmentation = 0.55
    dilation = 0.45
    mirroring = 0.20
    max_dilation = 3.0
    max_compression = 0.35
    reorder_mode = 5
    trajectory = 1
    micro_grain_ms = 20
    fade_min_ms = 5
    fade_max_ms = 70
    fuzzy_sensitivity = 0.55
    presetNote$ = "Poly-temporal interleave: odd/even streams woven into one line."
elsif preset = 6
    segment_length_ms = 130
    fragmentation = 0.60
    dilation = 0.40
    mirroring = 0.25
    max_dilation = 3.5
    max_compression = 0.30
    reorder_mode = 2
    trajectory = 2
    micro_grain_ms = 18
    fade_min_ms = 4
    fade_max_ms = 90
    fuzzy_sensitivity = 0.60
    presetNote$ = "Entropy injection: rules loosen across the file, order decays into chaos."
endif

# Truthful labels after presets have changed numeric option values.
if segment_mode = 1
    segmentModeName$ = "Adaptive onsets"
elsif segment_mode = 2
    segmentModeName$ = "Fixed grid"
else
    segmentModeName$ = "Pitch periods"
endif
if reorder_mode = 1
    reorderModeName$ = "Sequential"
elsif reorder_mode = 2
    reorderModeName$ = "Fuzzy nearest-profile chain"
elsif reorder_mode = 3
    reorderModeName$ = "Shuffle"
elsif reorder_mode = 4
    reorderModeName$ = "Retrograde order"
else
    reorderModeName$ = "Interleave (odd then even)"
endif
if trajectory = 1
    trajectoryName$ = "None"
elsif trajectory = 2
    trajectoryName$ = "Order to chaos"
else
    trajectoryName$ = "Chaos to order"
endif

# ============================================================
# PARAMETER VALIDATION
# ============================================================

if fuzzy_sensitivity < 0
    fuzzy_sensitivity = 0
elsif fuzzy_sensitivity > 1
    fuzzy_sensitivity = 1
endif
if fragmentation < 0
    fragmentation = 0
elsif fragmentation > 1
    fragmentation = 1
endif
if dilation < 0
    dilation = 0
elsif dilation > 1
    dilation = 1
endif
if mirroring < 0
    mirroring = 0
elsif mirroring > 1
    mirroring = 1
endif
if pitch_ceiling <= pitch_floor
    exitScript: "Pitch_ceiling (" + string$(pitch_ceiling) + " Hz) must be above Pitch_floor ("
        ... + string$(pitch_floor) + " Hz)."
endif
if max_compression >= 1
    exitScript: "Max_compression is the SHORTEST time factor and must be below 1 (e.g. 0.35)."
endif
if max_dilation <= 1
    exitScript: "Max_dilation is the LONGEST time factor and must be above 1 (e.g. 4.0)."
endif

# One Lengthen pass is kept inside 0.25x..3.0x. Compute how many chained
# passes are sufficient to reach the extrema allowed by this run.
passesDilate = ceiling(ln(max_dilation) / ln(3.0))
passesCompress = ceiling(ln(max_compression) / ln(0.25))
maxWarpPasses = max(1, max(passesDilate, passesCompress))
if maxWarpPasses > 8
    exitScript: "Requested warp range needs " + string$(maxWarpPasses) + " chained PSOLA passes. Keep Max_dilation / Max_compression within an 8-pass range."
endif

if safety_peak < 0
    safety_peak = 0
elsif safety_peak > 1
    safety_peak = 1
endif
if random_seed < 0
    random_seed = 0
elsif random_seed > 2147483647
    random_seed = 2147483647
endif

# ============================================================
# PREPARATION
# ============================================================

clearinfo
selectObject: src
nch = Get number of channels
fs = Get sampling frequency
nInputSamples = Get number of samples
dur = nInputSamples / fs
dt = 1 / fs
nyq = fs / 2
srcId$ = string$(src)
# Re-grid by sample index onto an exact 0-based domain.  This avoids tiny
# floating-point time-domain differences from becoming fuzzy-feature differences.
srcProc = Create Sound from formula: "ftr_source", nch, 0, dur, fs, "object[" + srcId$ + ",row,col]"

if dur < 0.25
    removeObject: srcProc
    exitScript: "Input is only " + fixed$(dur, 3) + " s. Fuzzy Time Re-Composer needs at least 0.25 s."
endif

# Analysis is mono, but rendering remains multichannel.  Use a mean fold-down
# unless cancellation makes it unreliable, then analyse the loudest real channel.
if nch = 1
    selectObject: srcProc
    snd = Copy: "ftr_analysis"
    analysisSource$ = "mono input"
else
    selectObject: srcProc
    fold = Convert to mono
    foldRms = Get root-mean-square: 0, 0
    maxChannelRms = 0
    loudestChannel = 1
    for ch from 1 to nch
        selectObject: srcProc
        tmpCh = Extract one channel: ch
        chRms = Get root-mean-square: 0, 0
        if chRms > maxChannelRms
            maxChannelRms = chRms
            loudestChannel = ch
        endif
        removeObject: tmpCh
    endfor
    if maxChannelRms > 0 and foldRms < 0.10 * maxChannelRms
        removeObject: fold
        selectObject: srcProc
        snd = Extract one channel: loudestChannel
        Rename: "ftr_analysis"
        analysisSource$ = "channel " + string$(loudestChannel) + " fallback"
    else
        snd = fold
        selectObject: snd
        Rename: "ftr_analysis"
        analysisSource$ = "mean fold-down"
    endif
endif

# Level-normalize the ANALYSIS COPY only.  All descriptors are intended to
# describe relative shape/content; rendering always uses untouched source channels.
selectObject: snd
analysisPeak = Get absolute extremum: 0, 0, "None"
if analysisPeak > 0
    Multiply: 0.5 / analysisPeak
endif

if random_seed = 0
    random_initializeSafelyAndUnpredictably()
    seedUsed = randomInteger(1, 2147483646)
    random_initializeWithSeedUnsafelyButPredictably(seedUsed)
else
    seedUsed = random_seed
    random_initializeWithSeedUnsafelyButPredictably(seedUsed)
endif

minWarpDur = 4.0 / pitch_floor
segLen = segment_length_ms / 1000
maxSeg = 400
maxGrain = 6000
# ============================================================
# STEP 1: SEGMENTATION
# ============================================================
bnd# = zero#(maxSeg + 1)
nBnd = 0

selectObject: snd
intGlobal = To Intensity: pitch_floor, 0.005, "yes"
nIntFrames = Get number of frames

if segment_mode = 1
    # -- adaptive onsets from the positive intensity derivative --------------
    selectObject: intGlobal
    dv# = zero#(nIntFrames)
    sumPos = 0
    sumPos2 = 0
    nPos = 0
    prev = Get value in frame: 1
    for f from 2 to nIntFrames
        cur = Get value in frame: f
        d = cur - prev
        prev = cur
        dv# [f] = d
        if d > 0
            sumPos += d
            sumPos2 += d * d
            nPos += 1
        endif
    endfor
    if nPos > 1
        mPos = sumPos / nPos
        vPos = (sumPos2 - nPos * mPos * mPos) / (nPos - 1)
        if vPos < 0
            vPos = 0
        endif
        sPos = sqrt(vPos)
    else
        mPos = 0
        sPos = 0
    endif
    onsetThresh = mPos + onset_sensitivity * sPos

    selectObject: intGlobal
    tStep = Get time step
    t1Frame = Get time from frame number: 1
    lastOnset = -1e30
    nBnd = 1
    bnd# [1] = 0
    for f from 2 to nIntFrames - 1
        if dv# [f] > onsetThresh and dv# [f] >= dv# [f - 1] and dv# [f] >= dv# [f + 1]
            tOn = t1Frame + (f - 1) * tStep
            if tOn - lastOnset >= segLen and tOn > segLen / 2 and tOn < dur - segLen / 2
                if nBnd < maxSeg
                    nBnd += 1
                    bnd# [nBnd] = tOn
                    lastOnset = tOn
                endif
            endif
        endif
    endfor
    nBnd += 1
    bnd# [nBnd] = dur

elsif segment_mode = 2
    # -- fixed grid ----------------------------------------------------------
    nBnd = 1
    bnd# [1] = 0
    t = segLen
    while t < dur - segLen / 2 and nBnd < maxSeg
        nBnd += 1
        bnd# [nBnd] = t
        t += segLen
    endwhile
    nBnd += 1
    bnd# [nBnd] = dur

else
    # -- pitch-period accumulation ------------------------------------------
    selectObject: snd
    pp = To PointProcess (periodic, cc): pitch_floor, pitch_ceiling
    nPts = Get number of points
    nBnd = 1
    bnd# [1] = 0
    acc = 0
    prevT = 0
    for p from 1 to nPts
        tp = Get time from index: p
        if tp > 0 and tp < dur
            acc += tp - prevT
            prevT = tp
            if acc >= segLen and nBnd < maxSeg and tp < dur - segLen / 2
                nBnd += 1
                bnd# [nBnd] = tp
                acc = 0
            endif
        endif
    endfor
    removeObject: pp
    nBnd += 1
    bnd# [nBnd] = dur
endif

# -- snap interior boundaries to zero crossings (grid / onset modes) --------
if segment_mode <> 3
    selectObject: snd
    for b from 2 to nBnd - 1
        z = Get nearest zero crossing: 1, bnd# [b]
        if z <> undefined and z > bnd# [b - 1] + 0.002 and z < bnd# [b + 1] - 0.002
            bnd# [b] = z
        endif
    endfor
endif

nSeg = nBnd - 1
if nSeg < 1
    removeObject: snd, intGlobal
    exitScript: "Segmentation produced no usable segments. Try a shorter Segment_length_ms."
endif

# ============================================================
# STEP 2: DESCRIPTORS AND FUZZY STATE MAPPING
# ============================================================
selectObject: snd
pitchGlobal = To Pitch: 0, pitch_floor, pitch_ceiling
selectObject: snd
harmGlobal = To Harmonicity (cc): 0.01, pitch_floor, 0.1, 1.0

rAttack# = zero#(nSeg)
rHarm#   = zero#(nSeg)
rMotion# = zero#(nSeg)
rHigh#  = zero#(nSeg)
rEntropy# = zero#(nSeg)
rLow#    = zero#(nSeg)
rSlope#  = zero#(nSeg)
segT0#   = zero#(nSeg)
segT1#   = zero#(nSeg)

nBands = 7
bandEdge# = zero#(nBands + 1)
bandEdge# [1] = 0
bandEdge# [2] = 250
bandEdge# [3] = 500
bandEdge# [4] = 1000
bandEdge# [5] = 2000
bandEdge# [6] = 4000
bandEdge# [7] = 8000
bandEdge# [8] = nyq
usableBands = 0
for k from 1 to nBands
    if bandEdge# [k + 1] > bandEdge# [k] and bandEdge# [k] < nyq
        usableBands += 1
    endif
endfor
if usableBands < 2
    usableBands = 2
endif

for i from 1 to nSeg
    t0 = bnd# [i]
    t1 = bnd# [i + 1]
    segT0# [i] = t0
    segT1# [i] = t1
    sdur = t1 - t0

    # ---- intensity attack and energy slope --------------------------------
    selectObject: intGlobal
    iMeanEarly = Get mean: t0, t0 + 0.35 * sdur, "energy"
    iMeanLate = Get mean: t1 - 0.35 * sdur, t1, "energy"
    iPeakEarly = Get maximum: t0, t0 + 0.35 * sdur, "parabolic"
    iStart = Get value at time: t0 + 0.02 * sdur, "linear"
    if iPeakEarly = undefined or iStart = undefined
        rAttack# [i] = 0
    else
        rAttack# [i] = iPeakEarly - iStart
    endif
    if iMeanEarly = undefined or iMeanLate = undefined
        rSlope# [i] = 0
    else
        rSlope# [i] = iMeanLate - iMeanEarly
    endif

    # ---- harmonicity -------------------------------------------------------
    selectObject: harmGlobal
    h = Get mean: t0, t1
    if h = undefined
        h = -200
    endif
    rHarm# [i] = h

    # ---- pitch motion (semitone dispersion) --------------------------------
    selectObject: pitchGlobal
    psd = Get standard deviation: t0, t1, "semitones"
    if psd = undefined
        psd = 0
    endif
    rMotion# [i] = psd

    # ---- spectral descriptors: low/HF energy ratios + coarse entropy ------
    selectObject: snd
    part = Extract part: t0, t1, "rectangular", 1, "no"
    spec = To Spectrum: "yes"
    eTot = Get band energy: 0, nyq
    if eTot <= 0
        eTot = 1e-30
    endif
    eLow = Get band energy: 0, 500
    eHigh = Get band energy: 2000, nyq
    rLow# [i] = eLow / eTot
    rHigh# [i] = eHigh / eTot
    hSum = 0
    for k from 1 to nBands
        lo = bandEdge# [k]
        hi = bandEdge# [k + 1]
        if hi > lo and lo < nyq
            if hi > nyq
                hi = nyq
            endif
            eB = Get band energy: lo, hi
            pB = eB / eTot
            if pB > 1e-12
                hSum -= pB * ln(pB)
            endif
        endif
    endfor
    rEntropy# [i] = hSum / ln(usableBands)
    removeObject: spec, part
endfor

# ---- normalise every descriptor across THIS file's segments ----------------
procedure normalise: .n
    .lo = 1e30
    .hi = -1e30
    for .k from 1 to .n
        if nrmIn# [.k] < .lo
            .lo = nrmIn# [.k]
        endif
        if nrmIn# [.k] > .hi
            .hi = nrmIn# [.k]
        endif
    endfor
    .range = .hi - .lo
    .mag = max(abs(.lo), abs(.hi))
    .tol = max(1e-4, 1e-4 * .mag)
    if .range < .tol
        for .k from 1 to .n
            nrmOut# [.k] = 0.5
        endfor
    else
        for .k from 1 to .n
            nrmOut# [.k] = (nrmIn# [.k] - .lo) / .range
        endfor
    endif
endproc

nrmIn# = zero#(nSeg)
nrmOut# = zero#(nSeg)

nAttack# = zero#(nSeg)
nHarm#   = zero#(nSeg)
nMotion# = zero#(nSeg)
nHigh#  = zero#(nSeg)
nEntropy# = zero#(nSeg)
nLow#    = zero#(nSeg)
nSlope#  = zero#(nSeg)

for k from 1 to nSeg
    nrmIn# [k] = rAttack# [k]
endfor
@normalise: nSeg
for k from 1 to nSeg
    nAttack# [k] = nrmOut# [k]
    nrmIn# [k] = rHarm# [k]
endfor
@normalise: nSeg
for k from 1 to nSeg
    nHarm# [k] = nrmOut# [k]
    nrmIn# [k] = rMotion# [k]
endfor
@normalise: nSeg
for k from 1 to nSeg
    nMotion# [k] = nrmOut# [k]
    nrmIn# [k] = rHigh# [k]
endfor
@normalise: nSeg
for k from 1 to nSeg
    nHigh# [k] = nrmOut# [k]
    nrmIn# [k] = rEntropy# [k]
endfor
@normalise: nSeg
for k from 1 to nSeg
    nEntropy# [k] = nrmOut# [k]
    nrmIn# [k] = rLow# [k]
endfor
@normalise: nSeg
for k from 1 to nSeg
    nLow# [k] = nrmOut# [k]
    nrmIn# [k] = rSlope# [k]
endfor
@normalise: nSeg
for k from 1 to nSeg
    nSlope# [k] = nrmOut# [k]
endfor

# ---- membership functions --------------------------------------------------
# Keep the neutral point fixed at 0.5.  Fuzzy_sensitivity controls contrast:
# low sensitivity gives a broad ramp; high sensitivity makes low/high evidence
# separate more sharply without turning a neutral 0.5 descriptor into "high".
muCentre = 0.5
muWidth = 0.80 - 0.60 * fuzzy_sensitivity
muLo = muCentre - muWidth / 2
muHi = muCentre + muWidth / 2

procedure muUp: .x
    if .x <= muLo
        .y = 0
    elsif .x >= muHi
        .y = 1
    else
        .y = (.x - muLo) / (muHi - muLo)
    endif
endproc

muT# = zero#(nSeg)
muS# = zero#(nSeg)
muM# = zero#(nSeg)
muHF# = zero#(nSeg)
muE# = zero#(nSeg)
muL# = zero#(nSeg)
muC# = zero#(nSeg)

for i from 1 to nSeg
    @muUp: nAttack# [i]
    muT# [i] = muUp.y
    @muUp: nHarm# [i]
    muS# [i] = muUp.y
    @muUp: nMotion# [i]
    muM# [i] = muUp.y
    @muUp: nHigh# [i]
    muHF# [i] = muUp.y
    @muUp: nEntropy# [i]
    muE# [i] = muUp.y
    @muUp: nLow# [i]
    muL# [i] = muUp.y
    @muUp: nSlope# [i]
    muC# [i] = muUp.y
endfor

# ============================================================
# STEP 3: TIME-REORDERING MATRIX
# ============================================================
order# = zero#(nSeg)
for i from 1 to nSeg
    order# [i] = i
endfor

if reorder_mode = 2
    # Greedy nearest-neighbour path through fuzzy descriptor space.
    used# = zero#(nSeg)
    cur = 1
    used# [1] = 1
    order# [1] = 1
    for k from 2 to nSeg
        bestD = 1e30
        bestJ = 0
        for j from 1 to nSeg
            if used# [j] = 0
                d = (muT# [cur] - muT# [j]) ^ 2 + (muS# [cur] - muS# [j]) ^ 2
                    ... + (muM# [cur] - muM# [j]) ^ 2 + (muHF# [cur] - muHF# [j]) ^ 2
                    ... + (muE# [cur] - muE# [j]) ^ 2 + (muL# [cur] - muL# [j]) ^ 2
                    ... + (muC# [cur] - muC# [j]) ^ 2
                if d < bestD
                    bestD = d
                    bestJ = j
                endif
            endif
        endfor
        order# [k] = bestJ
        used# [bestJ] = 1
        cur = bestJ
    endfor
elsif reorder_mode = 3
    # Fisher-Yates shuffle.
    for i from 1 to nSeg - 1
        j = randomInteger(i, nSeg)
        tmp = order# [i]
        order# [i] = order# [j]
        order# [j] = tmp
    endfor
elsif reorder_mode = 4
    for i from 1 to nSeg
        order# [i] = nSeg - i + 1
    endfor
elsif reorder_mode = 5
    k = 0
    i = 1
    while i <= nSeg
        k += 1
        order# [k] = i
        i += 2
    endwhile
    i = 2
    while i <= nSeg
        k += 1
        order# [k] = i
        i += 2
    endwhile
endif

# Map each source segment to its position in the OUTPUT order.  Macro trajectory
# weights therefore progress along the re-composed timeline, not the source file.
slot# = zero#(nSeg)
for k from 1 to nSeg
    slot# [order# [k]] = k
endfor

# Derive one render seed after order selection.  Each channel then receives the
# same per-segment PSOLA and micro-grain seeds, preserving channel relationships.
renderSeed = randomInteger(1, 2147483646)

# ============================================================
# STEP 4: RULE BASE -> WARP FACTOR + GESTURE
# ============================================================
# Gestures: 1 preserve, 2 dilate, 3 compress, 4 granulate, 5 retrograde, 6 ostinato
warp# = zero#(nSeg)
act#  = zero#(nSeg)
# Decision confidence: (best - runner-up) / best. A gesture that wins
# 0.71 to 0.70 is not the same decision as one that wins 0.90 to 0.05,
# and the Picture output distinguishes the two.
actMargin# = zero#(nSeg)
fadeS# = zero#(nSeg)
chaos# = zero#(nSeg)
sumA1 = 0
sumA2 = 0
sumA3 = 0
sumA4 = 0
sumA5 = 0
sumA6 = 0

for i from 1 to nSeg
    # Macro trajectory is defined over OUTPUT position.
    if nSeg > 1
        pos = (slot# [i] - 1) / (nSeg - 1)
    else
        pos = 0
    endif
    if trajectory = 2
        c = pos
    elsif trajectory = 3
        c = 1 - pos
    else
        c = 0.5
    endif
    chaos# [i] = c

    # Bias weights are centred on 1.0 so that no rule is structurally favoured.
    fragW = (0.4 + 1.2 * fragmentation) * (0.7 + 0.6 * c)
    dilW  = (0.4 + 1.2 * dilation) * (1.3 - 0.6 * c)
    mirW  = 0.4 + 1.2 * mirroring
    ostW  = (0.4 + 1.2 * (1 - fragmentation)) * 0.75
    prsW  = 1.4 - 0.8 * fragmentation

    aPreserve = muS# [i] * (1 - muT# [i]) * prsW
    aDilate   = muS# [i] * (1 - muM# [i]) * dilW
    # Fragmentation splits two ways: HF-rich non-transients compress, while
    # transient/entropic material is preferentially granulated.
    aCompress = muHF# [i] * (1 - 0.60 * muT# [i]) * fragW
    aGranular = muT# [i] * (0.50 + 0.50 * muE# [i]) * fragW * (0.80 + 0.60 * fragmentation)
    aRetro    = min(muC# [i], 1 - muM# [i]) * mirW
    # Strong dilation bias should not be defeated by the low/sustain ostinato rule.
    aOstinato = muS# [i] * muL# [i] * ostW * (1 - 0.75 * dilation)

    wSum = aPreserve + aDilate + aCompress + aGranular + aRetro + aOstinato
    if wSum < 1e-6
        warp# [i] = 1
    else
        logF = aDilate * ln(max_dilation)
            ... + aCompress * ln(max_compression)
            ... + aGranular * ln(max(max_compression, 0.7))
            ... + aPreserve * 0 + aRetro * 0 + aOstinato * 0
        warp# [i] = exp(logF / wSum)
    endif
    if warp# [i] > max_dilation
        warp# [i] = max_dilation
    elsif warp# [i] < max_compression
        warp# [i] = max_compression
    endif

    # Same argmax as before (ties resolve to the earliest rule), but the
    # runner-up is retained so decision confidence can be reported.
    aVec# = {aPreserve, aDilate, aCompress, aGranular, aRetro, aOstinato}
    best = 0
    bi = 1
    for q from 1 to 6
        if aVec# [q] > best
            best = aVec# [q]
            bi = q
        endif
    endfor
    second = 0
    for q from 1 to 6
        if q <> bi and aVec# [q] > second
            second = aVec# [q]
        endif
    endfor
    if best > 1e-9
        actMargin# [i] = (best - second) / best
    else
        actMargin# [i] = 0
    endif
    act# [i] = bi
    sumA1 += aPreserve
    sumA2 += aDilate
    sumA3 += aCompress
    sumA4 += aGranular
    sumA5 += aRetro
    sumA6 += aOstinato

    # Sustain gets long joins; transients short joins.
    fadeS# [i] = (fade_min_ms + (fade_max_ms - fade_min_ms) * muS# [i] * (1 - muT# [i])) / 1000
endfor

# ============================================================
# STEP 5: RENDER GRAINS PER CHANNEL
# ============================================================
warpApplied = 0
warpSkipped = 0
warpClampedPasses = 0
grainCapHit = 0
nGrainMaster = 0
outDur = 0
bufId# = zero#(nch)

procedure warpSound: .id, .factor, .key
    .out = .id
    .own = 0
    .rem = .factor
    .passes = 0
    .ok = 1
    while abs(.rem - 1) > 0.02 and .passes < maxWarpPasses and .ok = 1
        selectObject: .out
        .dd = Get total duration
        if .dd < minWarpDur
            .ok = 0
        else
            .f = .rem
            if .f > 3.0
                .f = 3.0
                if renderCh = 1
                    warpClampedPasses += 1
                endif
            elsif .f < 0.25
                .f = 0.25
                if renderCh = 1
                    warpClampedPasses += 1
                endif
            endif
            # Reset per segment/pass so every source channel uses the same PSOLA
            # stochastic path independent of previous signal content.
            .s = 1 + ((renderSeed + .key * 1009 + .passes * 7919) mod 2147483646)
            random_initializeWithSeedUnsafelyButPredictably(.s)
            selectObject: .out
            .new = Lengthen (overlap-add): pitch_floor, pitch_ceiling, .f
            if .own = 1
                removeObject: .out
            endif
            .out = .new
            .own = 1
            .rem = .rem / .f
            .passes += 1
        endif
    endwhile
    if renderCh = 1
        if .passes > 0
            warpApplied += 1
        elsif abs(.factor - 1) > 0.02
            warpSkipped += 1
        endif
    endif
endproc

for renderCh from 1 to nch
    selectObject: srcProc
    if nch = 1
        workChannel = Copy: "ftr_channel"
    else
        workChannel = Extract one channel: renderCh
        Rename: "ftr_channel"
    endif

    gId#    = zero#(maxGrain)
    gDur#   = zero#(maxGrain)
    gFade#  = zero#(maxGrain)
    gSrcT0# = zero#(maxGrain)
    gSrcT1# = zero#(maxGrain)
    gRev#   = zero#(maxGrain)
    gAct#   = zero#(maxGrain)
    nGrain = 0

    for k from 1 to nSeg
        i = order# [k]
        t0 = segT0# [i]
        t1 = segT1# [i]
        a = act# [i]
        wf = warp# [i]

        selectObject: workChannel
        base = Extract part: t0, t1, "rectangular", 1, "no"

        if a = 5
            @warpSound: base, wf, i
            fwd = warpSound.out
            if warpSound.own = 1
                removeObject: base
            endif
            selectObject: fwd
            rev = Copy: "ftr_rev"
            Reverse
            if nGrain + 2 <= maxGrain
                selectObject: fwd
                nGrain += 1
                gId# [nGrain] = fwd
                gDur# [nGrain] = Get total duration
                gFade# [nGrain] = fadeS# [i] * 1.6
                gSrcT0# [nGrain] = t0
                gSrcT1# [nGrain] = t1
                gRev# [nGrain] = 0
                gAct# [nGrain] = 5
                selectObject: rev
                nGrain += 1
                gId# [nGrain] = rev
                gDur# [nGrain] = Get total duration
                gFade# [nGrain] = fadeS# [i] * 1.6
                gSrcT0# [nGrain] = t1
                gSrcT1# [nGrain] = t0
                gRev# [nGrain] = 1
                gAct# [nGrain] = 5
            else
                grainCapHit = 1
                removeObject: fwd, rev
            endif

        elsif a = 4
            @warpSound: base, wf, i
            wsnd = warpSound.out
            if warpSound.own = 1
                removeObject: base
            endif
            selectObject: wsnd
            wdur = Get total duration
            gLen = micro_grain_ms / 1000 * (1.2 - 0.6 * chaos# [i])
            if gLen < 0.006
                gLen = 0.006
            endif
            nMicro = floor(wdur / gLen)
            if nMicro < 2
                nMicro = 1
                gLen = wdur
            endif
            mIdx# = zero#(nMicro)
            for m from 1 to nMicro
                mIdx# [m] = m
            endfor
            microSeed = 1 + ((renderSeed + i * 104729) mod 2147483646)
            random_initializeWithSeedUnsafelyButPredictably(microSeed)
            for m from 1 to nMicro - 1
                j = randomInteger(m, nMicro)
                tmp = mIdx# [m]
                mIdx# [m] = mIdx# [j]
                mIdx# [j] = tmp
            endfor
            for m from 1 to nMicro
                mi = mIdx# [m]
                mt0 = (mi - 1) * gLen
                mt1 = mt0 + gLen
                if mt1 > wdur
                    mt1 = wdur
                endif
                if mt1 - mt0 > 3 * dt and nGrain < maxGrain
                    selectObject: wsnd
                    mg = Extract part: mt0, mt1, "rectangular", 1, "no"
                    nGrain += 1
                    gId# [nGrain] = mg
                    gDur# [nGrain] = Get total duration
                    gFade# [nGrain] = fade_min_ms / 1000
                    gSrcT0# [nGrain] = t0 + (t1 - t0) * mt0 / wdur
                    gSrcT1# [nGrain] = t0 + (t1 - t0) * mt1 / wdur
                    gRev# [nGrain] = 0
                    gAct# [nGrain] = 4
                elsif nGrain >= maxGrain
                    grainCapHit = 1
                endif
            endfor
            removeObject: wsnd

        elsif a = 6
            @warpSound: base, wf, i
            wsnd = warpSound.out
            if warpSound.own = 1
                removeObject: base
            endif
            nRep = 2 + floor(2 * muS# [i])
            for r from 1 to nRep
                if nGrain < maxGrain
                    selectObject: wsnd
                    cp = Copy: "ftr_ost"
                    nGrain += 1
                    gId# [nGrain] = cp
                    gDur# [nGrain] = Get total duration
                    gFade# [nGrain] = fadeS# [i]
                    gSrcT0# [nGrain] = t0
                    gSrcT1# [nGrain] = t1
                    gRev# [nGrain] = 0
                    gAct# [nGrain] = 6
                else
                    grainCapHit = 1
                endif
            endfor
            removeObject: wsnd

        else
            @warpSound: base, wf, i
            wsnd = warpSound.out
            if warpSound.own = 1
                removeObject: base
            endif
            if nGrain < maxGrain
                selectObject: wsnd
                nGrain += 1
                gId# [nGrain] = wsnd
                gDur# [nGrain] = Get total duration
                gFade# [nGrain] = fadeS# [i]
                gSrcT0# [nGrain] = t0
                gSrcT1# [nGrain] = t1
                gRev# [nGrain] = 0
                gAct# [nGrain] = a
            else
                grainCapHit = 1
                removeObject: wsnd
            endif
        endif
    endfor

    if nGrain < 1
        removeObject: workChannel, snd, srcProc, intGlobal, pitchGlobal, harmGlobal
        exitScript: "No grains were produced. Try a shorter Segment_length_ms."
    endif

    if renderCh = 1
        nGrainMaster = nGrain
        ov# = zero#(nGrain + 1)
        ov# [1] = min(fade_min_ms / 1000, 0.45 * gDur# [1])
        for k from 1 to nGrain - 1
            o = min(gFade# [k], gFade# [k + 1])
            o = min(o, 0.45 * gDur# [k])
            o = min(o, 0.45 * gDur# [k + 1])
            if o < 2 * dt
                o = min(2 * dt, 0.45 * gDur# [k])
            endif
            ov# [k + 1] = round(o / dt) * dt
        endfor
        ov# [nGrain + 1] = min(fade_min_ms / 1000, 0.45 * gDur# [nGrain])
        ov# [1] = round(ov# [1] / dt) * dt
        ov# [nGrain + 1] = round(ov# [nGrain + 1] / dt) * dt

        place# = zero#(nGrain)
        place# [1] = 0
        for k from 2 to nGrain
            p = place# [k - 1] + gDur# [k - 1] - ov# [k]
            if p < place# [k - 1]
                p = place# [k - 1]
            endif
            place# [k] = round(p / dt) * dt
        endfor
        outDur = place# [nGrain] + gDur# [nGrain]
        outP0# = zero#(nGrain)
        outP1# = zero#(nGrain)
        for k from 1 to nGrain
            outP0# [k] = place# [k]
            outP1# [k] = place# [k] + gDur# [k]
        endfor

        if outDur > 900
            for k from 1 to nGrain
                removeObject: gId# [k]
            endfor
            removeObject: workChannel, snd, srcProc, intGlobal, pitchGlobal, harmGlobal
            exitScript: "Projected output is " + fixed$(outDur, 1) + " s (over the 900 s guard). Lower Max_dilation or shorten the input."
        endif
    else
        if nGrain <> nGrainMaster
            for k from 1 to nGrain
                removeObject: gId# [k]
            endfor
            removeObject: workChannel, snd, srcProc, intGlobal, pitchGlobal, harmGlobal
            exitScript: "Internal multichannel render mismatch. Try a less extreme time-warp setting."
        endif
    endif

    # Apply the canonical crossfades to this channel's grains.
    for k from 1 to nGrain
        d = gDur# [k]
        fadeI = ov# [k]
        fadeO = ov# [k + 1]
        if fadeI + fadeO > d
            sc = d / (fadeI + fadeO)
            fadeI = fadeI * sc * 0.98
            fadeO = fadeO * sc * 0.98
        endif
        if fadeI < dt
            fadeI = dt
        endif
        if fadeO < dt
            fadeO = dt
        endif
        fiS$ = fixed$(fadeI, 9)
        foS$ = fixed$(fadeO, 9)
        d$ = fixed$(d, 9)
        if crossfade_law = 1
            fadeIn$ = "(0.5 - 0.5 * cos(pi * x / " + fiS$ + "))"
            fadeOut$ = "(0.5 - 0.5 * cos(pi * (" + d$ + " - x) / " + foS$ + "))"
        else
            fadeIn$ = "sin(0.5 * pi * x / " + fiS$ + ")"
            fadeOut$ = "sin(0.5 * pi * (" + d$ + " - x) / " + foS$ + ")"
        endif
        f$ = "self * (if x < " + fiS$ + " then " + fadeIn$ + " else 1 fi)"
            ... + " * (if x > " + d$ + " - " + foS$ + " then " + fadeOut$ + " else 1 fi)"
        selectObject: gId# [k]
        Formula: f$
    endfor

    buf = Create Sound from formula: "ftr_out_ch_" + string$(renderCh), 1, 0, outDur, fs, "0"
    for k from 1 to nGrain
        p0 = place# [k]
        p1 = p0 + gDur# [k]
        if p1 > outDur
            p1 = outDur
        endif
        selectObject: buf
        Formula (part): p0, p1, 1, 1, "self + object(" + string$(gId# [k]) + ", x - " + fixed$(p0, 9) + ")"
    endfor
    bufId# [renderCh] = buf

    for k from 1 to nGrain
        removeObject: gId# [k]
    endfor
    removeObject: workChannel
endfor

# Recombine rendered mono channels in their original order.
if nch = 1
    result = bufId# [1]
else
    selectObject: bufId# [1]
    for ch from 2 to nch
        plusObject: bufId# [ch]
    endfor
    result = Combine to stereo
    for ch from 1 to nch
        removeObject: bufId# [ch]
    endfor
endif

selectObject: result
peakRaw = Get absolute extremum: 0, 0, "Sinc70"
gainApplied = 1
if safety_peak > 0 and peakRaw > safety_peak and peakRaw > 0
    gainApplied = safety_peak / peakRaw
    Multiply: gainApplied
endif
peakFinal = Get absolute extremum: 0, 0, "Sinc70"
outName$ = srcName$ + "_fuzzytime"
Rename: outName$
result = selected("Sound")
outChannels = Get number of channels

# Actual warp statistics are needed by both visualization and report.
meanWarp = 0
minWarp = 1e30
maxWarp = -1e30
for i from 1 to nSeg
    meanWarp += warp# [i]
    if warp# [i] < minWarp
        minWarp = warp# [i]
    endif
    if warp# [i] > maxWarp
        maxWarp = warp# [i]
    endif
endfor
meanWarp = meanWarp / nSeg

# Gesture census and decision-confidence census are needed by BOTH the Picture
# output and the Info report, so they are computed once, here, before either.
nPreserve = 0
nDilate = 0
nCompress = 0
nGranulate = 0
nRetro = 0
nOstinato = 0
closeCalls = 0
closeCallLimit = 0.25
for i from 1 to nSeg
    a = act# [i]
    if a = 1
        nPreserve += 1
    elsif a = 2
        nDilate += 1
    elsif a = 3
        nCompress += 1
    elsif a = 4
        nGranulate += 1
    elsif a = 5
        nRetro += 1
    else
        nOstinato += 1
    endif
    if actMargin# [i] < closeCallLimit
        closeCalls += 1
    endif
endfor

procedure gestureColour: .a
    # Colour has one semantic meaning throughout the decision/time maps:
    # the winning discrete gesture.
    if .a = 1
        .r = 0.48
        .g = 0.52
        .b = 0.58
    elsif .a = 2
        .r = 0.24
        .g = 0.50
        .b = 0.80
    elsif .a = 3
        .r = 0.88
        .g = 0.48
        .b = 0.20
    elsif .a = 4
        .r = 0.26
        .g = 0.66
        .b = 0.42
    elsif .a = 5
        .r = 0.64
        .g = 0.36
        .b = 0.75
    else
        .r = 0.78
        .g = 0.30
        .b = 0.36
    endif
endproc

# ============================================================
# STEP 7: VISUALISATION
# ============================================================
if draw_analysis
    Erase all
    Colour: "Black"
    Font size: 10
    Line width: 1
    Solid line

    # ----------------------------------------------------------
    # DISPLAY COPY OF THE SOURCE
    # The analysis object (snd) is level-normalised to 0.5 peak for
    # descriptor stability, so it must NOT be used as the "Source"
    # waveform: it would show every input at the same apparent level.
    # This is an un-normalised copy that follows the same channel
    # decision the analysis made, so segment boundaries still line up.
    # ----------------------------------------------------------
    if nch = 1
        selectObject: srcProc
        vizSrc = Copy: "ftr_viz_source"
    elsif analysisSource$ = "mean fold-down"
        selectObject: srcProc
        vizSrc = Convert to mono
        Rename: "ftr_viz_source"
    else
        selectObject: srcProc
        vizSrc = Extract one channel: loudestChannel
        Rename: "ftr_viz_source"
    endif
    selectObject: vizSrc
    peakSrcViz = Get absolute extremum: 0, 0, "None"

    # Source and Output share one amplitude scale, otherwise the
    # before/after comparison is meaningless.
    sharedAmp = 1.18 * max(peakSrcViz, peakFinal)
    if sharedAmp < 0.05
        sharedAmp = 0.05
    endif

    # ----------------------------------------------------------
    # TITLE
    # ----------------------------------------------------------
    Select outer viewport: 0, 8, 0, 0.46
    Axes: 0, 1, 0, 1
    Font size: 12
    Colour: "Black"
    Text: 0.5, "centre", 0.68, "half", "##Fuzzy Time Re-Composer##"
    Font size: 7
    Colour: "{0.35, 0.35, 0.52}"
    Text: 0.5, "centre", -1.30, "half", "Fuzzy Time Recomposer.praat  |  " + preset$ + "  |  " + segmentModeName$ + " / " + reorderModeName$

    # ----------------------------------------------------------
    # SOURCE / SEGMENTATION
    # ----------------------------------------------------------
    Select outer viewport: 0, 8, 0.54, 1.66
    Select inner viewport: 0.55, 7.75, 0.71, 1.50
    Axes: 0, dur, -sharedAmp, sharedAmp
    Paint rectangle: "{0.97, 0.97, 0.97}", 0, dur, -sharedAmp, sharedAmp

    # Dense segmentations read better as alternating bands than as a
    # comb of hairlines; sparse ones read better as explicit boundaries.
    if nSeg > 60
        for i from 1 to nSeg
            if i mod 2 = 0
                Paint rectangle: "{0.92, 0.93, 0.94}", segT0# [i], segT1# [i], -sharedAmp, sharedAmp
            endif
        endfor
    endif

    Colour: "{0.84, 0.84, 0.84}"
    Draw line: 0, 0, dur, 0
    selectObject: vizSrc
    Colour: "{0.56, 0.56, 0.56}"
    Draw: 0, dur, -sharedAmp, sharedAmp, "no", "Curve"
    Select outer viewport: 0, 8, 0.54, 1.66
    Select inner viewport: 0.55, 7.75, 0.71, 1.50
    Axes: 0, dur, -sharedAmp, sharedAmp

    if nSeg <= 60
        Colour: "{0.60, 0.60, 0.65}"
        Line width: 0.7
        for i from 1 to nSeg
            Draw line: segT0# [i], -sharedAmp, segT0# [i], sharedAmp
        endfor
        Line width: 1
    endif

    Colour: "Black"
    Draw inner box
    Font size: 7
    Text top: "yes", "##Source / segmentation##"
    Font size: 6
    Text left: "yes", "Amplitude (+-" + fixed$(sharedAmp, 2) + ")"
    Marks bottom: 6, "yes", "yes", "no"
    Axes: 0, dur, -sharedAmp, sharedAmp
    Colour: "{0.28, 0.28, 0.28}"
    if nSeg > 60
        segNote$ = "alternating bands = segments"
    else
        segNote$ = "vertical lines = segment starts"
    endif
    Text: 0.01 * dur, "left", 0.80 * sharedAmp, "half", string$(nSeg) + " segments  |  " + segmentModeName$ + "  |  " + segNote$ + "  |  display " + analysisSource$ + ", unnormalised"

    # ----------------------------------------------------------
    # FUZZY MEMBERSHIPS
    # One row per fuzzy set, one cell per segment, shade = mu.
    # This is the inference INPUT; the decision map below is its output.
    # Greyscale only, so that colour keeps its single meaning (gesture).
    # ----------------------------------------------------------
    muName$# = {"transient", "sustain", "motion", "HF", "entropy", "low", "rise"}

    Select outer viewport: 0, 8, 1.72, 2.68
    Select inner viewport: 0.55, 7.75, 1.88, 2.62
    Axes: 0, dur, 0, 7
    Paint rectangle: "{0.97, 0.97, 0.97}", 0, dur, 0, 7

    for i from 1 to nSeg
        for r from 1 to 7
            if r = 1
                muVal = muT# [i]
            elsif r = 2
                muVal = muS# [i]
            elsif r = 3
                muVal = muM# [i]
            elsif r = 4
                muVal = muHF# [i]
            elsif r = 5
                muVal = muE# [i]
            elsif r = 6
                muVal = muL# [i]
            else
                muVal = muC# [i]
            endif
            muShade = 0.97 - 0.72 * muVal
            muCell$ = "{" + fixed$(muShade, 2) + ", " + fixed$(muShade, 2) + ", " + fixed$(muShade, 2) + "}"
            Paint rectangle: muCell$, segT0# [i], segT1# [i], 7 - r, 8 - r
        endfor
    endfor

    Colour: "{0.82, 0.82, 0.82}"
    Line width: 0.5
    for r from 1 to 6
        Draw line: 0, r, dur, r
    endfor
    Line width: 1

    Colour: "Black"
    Draw inner box
    Font size: 7
    Text top: "yes", "##Fuzzy memberships##"
    Font size: 5
    Colour: "{0.35, 0.35, 0.35}"
    for r from 1 to 7
        Text: -0.012 * dur, "right", 7.5 - r, "half", muName$# [r]
    endfor
    Font size: 6
    Colour: "{0.30, 0.30, 0.30}"
    Text: dur, "right", 7.42, "half", "shade: white = 0, dark = 1  |  x axis shared with Source"

    # ----------------------------------------------------------
    # GESTURE LEGEND
    # Kept outside the decision map so the map can use its full height.
    # ----------------------------------------------------------
    Select outer viewport: 0, 8, 2.70, 2.94
    Axes: 0, 1, 0, 1
    legendX# = {0.069, 0.153, 0.226, 0.310, 0.399, 0.494}
    legendLabel$# = {"preserve", "dilate", "compress", "granulate", "retrograde", "ostinato"}
    Font size: 6
    for a from 1 to 6
        @gestureColour: a
        markerColour$ = "{" + fixed$(gestureColour.r,2) + ", " + fixed$(gestureColour.g,2) + ", " + fixed$(gestureColour.b,2) + "}"
        Paint circle (mm): markerColour$, legendX# [a], 0.5, 0.85
        Colour: "{0.28, 0.28, 0.28}"
        Text: legendX# [a] + 0.013, "left", 0.5, "half", legendLabel$# [a]
    endfor
    Colour: "{0.42, 0.42, 0.42}"
    Text: 0.60, "left", 0.5, "half", "filled = clear win  |  ring = close call, " + string$(closeCalls) + "/" + string$(nSeg)

    # ----------------------------------------------------------
    # FUZZY DECISION MAP
    # x = source time, bar spans the actual segment (so segment length
    #     is visible, not just its centre)
    # y = log2(defuzzified warp factor), balanced around the 1x line
    # colour = winning discrete gesture
    # fill = decision confidence (margin over the runner-up rule)
    # ----------------------------------------------------------
    ln2 = ln(2)
    actualLogMin = ln(max(minWarp, 0.25)) / ln2
    actualLogMax = ln(max(maxWarp, 0.25)) / ln2
    dataLogMin = min(actualLogMin, 0)
    dataLogMax = max(actualLogMax, 0)
    logSpan = dataLogMax - dataLogMin
    decisionYmin = dataLogMin - 0.14 * logSpan
    decisionYmax = dataLogMax + 0.14 * logSpan
    # Absolute floor only, so a narrow warp range is not stretched into
    # false drama and a wide one is not squashed by reserved headroom.
    if decisionYmax - decisionYmin < 0.60
        decisionPad = (0.60 - (decisionYmax - decisionYmin)) / 2
        decisionYmin = decisionYmin - decisionPad
        decisionYmax = decisionYmax + decisionPad
    endif

    if nSeg <= 60
        decisionRadius = 1.55
    elsif nSeg <= 120
        decisionRadius = 1.25
    elsif nSeg <= 220
        decisionRadius = 1.05
    else
        decisionRadius = 0.90
    endif

    Select outer viewport: 0, 8, 2.96, 4.28
    Select inner viewport: 0.55, 7.75, 3.13, 4.12
    Axes: 0, dur, decisionYmin, decisionYmax
    Paint rectangle: "{0.97, 0.97, 0.97}", 0, dur, decisionYmin, decisionYmax

    # Factor references, full panel width.
    Colour: "{0.86, 0.86, 0.86}"
    Line width: 0.6
    for refExp from -2 to 3
        if refExp >= decisionYmin and refExp <= decisionYmax
            Draw line: 0, refExp, dur, refExp
        endif
    endfor
    Colour: "{0.42, 0.42, 0.42}"
    Line width: 1.2
    Draw line: 0, 0, dur, 0
    Line width: 1

    # Pass 1: neutral stems only, so that no stem is drawn over a marker.
    Colour: "{0.74, 0.74, 0.74}"
    Line width: 0.55
    for i from 1 to nSeg
        xMid = 0.5 * (segT0# [i] + segT1# [i])
        yWarp = ln(max(warp# [i], 0.25)) / ln2
        Draw line: xMid, 0, xMid, yWarp
    endfor
    Line width: 1

    # Pass 2: segment-span bars and gesture markers.
    for i from 1 to nSeg
        xMid = 0.5 * (segT0# [i] + segT1# [i])
        yWarp = ln(max(warp# [i], 0.25)) / ln2
        @gestureColour: act# [i]
        markerColour$ = "{" + fixed$(gestureColour.r,2) + ", " + fixed$(gestureColour.g,2) + ", " + fixed$(gestureColour.b,2) + "}"
        Colour: markerColour$
        Line width: 1.5
        Draw line: segT0# [i], yWarp, segT1# [i], yWarp
        Line width: 1
        if actMargin# [i] >= closeCallLimit
            Paint circle (mm): markerColour$, xMid, yWarp, decisionRadius
        else
            Paint circle (mm): "{0.97, 0.97, 0.97}", xMid, yWarp, decisionRadius
            Colour: markerColour$
            Line width: 1.1
            Draw circle (mm): xMid, yWarp, decisionRadius
            Line width: 1
        endif
    endfor

    Colour: "Black"
    Draw inner box
    Font size: 7
    Text top: "yes", "##Fuzzy decision map##"
    Font size: 6
    Text left: "yes", "Warp factor"
    Marks bottom: 6, "yes", "yes", "no"

    # Factor labels belong outside the box, not on top of the data.
    Font size: 5.5
    Colour: "Black"
    for refExp from -2 to 3
        if refExp >= decisionYmin and refExp <= decisionYmax
            if refExp < 0
                refLabel$ = fixed$(2 ^ refExp, 2) + "x"
            else
                refLabel$ = fixed$(2 ^ refExp, 0) + "x"
            endif
            One mark left: refExp, "no", "yes", "no", refLabel$
        endif
    endfor
    Font size: 6
    Colour: "{0.30, 0.30, 0.30}"
    Text: 0.01 * dur, "left", decisionYmax - 0.07 * (decisionYmax - decisionYmin), "half", "bar = segment span  |  y = defuzzified warp"

    # ----------------------------------------------------------
    # TEMPORAL REMAPPING
    # source interval -> output interval for every rendered grain.
    # Very large maps are visually thinned, never DSP-thinned.
    # ----------------------------------------------------------
    mapStep = 1
    if nGrainMaster > 900
        mapStep = 4
    elsif nGrainMaster > 600
        mapStep = 3
    elsif nGrainMaster > 300
        mapStep = 2
    endif
    remapYmin = -0.04 * outDur
    remapYmax = 1.10 * outDur

    Select outer viewport: 0, 8, 4.36, 5.82
    Select inner viewport: 0.55, 7.75, 4.53, 5.52
    Axes: 0, dur, remapYmin, remapYmax
    Paint rectangle: "{0.97, 0.97, 0.97}", 0, dur, remapYmin, remapYmax

    # Identity mapping. The two axes have different scales, so this is a
    # data reference, not a 45-degree diagonal; it is labelled as such.
    Colour: "{0.72, 0.72, 0.76}"
    Line width: 0.8
    Dotted line
    Draw line: 0, 0, min(dur, outDur), min(dur, outDur)
    Solid line
    Line width: 1

    Line width: 1.15
    k = 1
    while k <= nGrainMaster
        @gestureColour: gAct# [k]
        Colour: "{" + fixed$(gestureColour.r,2) + ", " + fixed$(gestureColour.g,2) + ", " + fixed$(gestureColour.b,2) + "}"
        Draw line: gSrcT0# [k], outP0# [k], gSrcT1# [k], outP1# [k]
        k += mapStep
    endwhile
    Line width: 1

    Colour: "Black"
    Draw inner box
    Font size: 7
    Text top: "yes", "##Temporal remapping##"
    Font size: 6
    Text left: "yes", "Output time (s)"
    Text bottom: "yes", "Source time (s)"
    Marks bottom: 6, "yes", "yes", "no"
    Marks left: 4, "yes", "yes", "no"
    Axes: 0, dur, remapYmin, remapYmax
    Colour: "{0.30, 0.30, 0.30}"
    if mapStep = 1
        remapNote$ = "dotted line = identity (same time in and out)  |  downward run = retrograde"
    else
        remapNote$ = "dotted line = identity  |  downward run = retrograde  |  every " + string$(mapStep) + "th grain drawn"
    endif
    Text: 0.01 * dur, "left", remapYmax - 0.06 * (remapYmax - remapYmin), "half", remapNote$

    # ----------------------------------------------------------
    # OUTPUT
    # Same amplitude scale as the Source panel. The waveform colour is
    # deliberately neutral: blue is the "dilate" gesture elsewhere.
    # ----------------------------------------------------------
    Select outer viewport: 0, 8, 5.92, 7.10
    Select inner viewport: 0.55, 7.75, 6.09, 6.80
    Axes: 0, outDur, -sharedAmp, sharedAmp
    Paint rectangle: "{0.97, 0.97, 0.97}", 0, outDur, -sharedAmp, sharedAmp
    Colour: "{0.84, 0.84, 0.84}"
    Draw line: 0, 0, outDur, 0
    selectObject: result
    Colour: "{0.30, 0.30, 0.34}"
    Draw: 0, outDur, -sharedAmp, sharedAmp, "no", "Curve"
    Select outer viewport: 0, 8, 5.92, 7.10
    Select inner viewport: 0.55, 7.75, 6.09, 6.80
    Axes: 0, outDur, -sharedAmp, sharedAmp
    Colour: "Black"
    Draw inner box
    Font size: 7
    Text top: "yes", "##Output##"
    Font size: 6
    Text left: "yes", "Amplitude (+-" + fixed$(sharedAmp, 2) + ")"
    Text bottom: "yes", "Output time (s)"
    Marks bottom: 6, "yes", "yes", "no"
    Colour: "{0.28, 0.28, 0.28}"
    Text: 0.01 * outDur, "left", 0.80 * sharedAmp, "half", "channels " + string$(nch) + " -> " + string$(outChannels) + "  |  same amplitude scale as Source  |  peak " + fixed$(peakFinal,3)

    # ----------------------------------------------------------
    # SUMMARY
    # ----------------------------------------------------------
    Select outer viewport: 0, 8, 7.20, 8.14
    Select inner viewport: 0.30, 7.80, 7.27, 8.07
    Axes: 0, 1, 0, 1
    Paint rectangle: "{0.94, 0.94, 0.94}", 0, 1, 0, 1
    Colour: "{0.48, 0.48, 0.48}"
    Draw rectangle: 0, 1, 0, 1
    Font size: 7
    Colour: "Black"
    Text: 0.02, "left", 0.84, "half", "##Summary##"
    Font size: 6
    Colour: "{0.28, 0.28, 0.28}"
    Text: 0.02, "left", 0.58, "half", "Segments " + string$(nSeg) + "  |  grains " + string$(nGrainMaster) + "  |  reorder " + reorderModeName$ + "  |  seed " + string$(seedUsed)
    Text: 0.02, "left", 0.35, "half", "Duration " + fixed$(dur,2) + " -> " + fixed$(outDur,2) + " s  |  warp " + fixed$(minWarp,2) + "-" + fixed$(maxWarp,2) + "x  |  ch " + string$(nch) + " -> " + string$(outChannels) + "  |  peak " + fixed$(peakRaw,3) + " -> " + fixed$(peakFinal,3)
    Text: 0.02, "left", 0.12, "half", "Gestures: preserve " + string$(nPreserve) + "  dilate " + string$(nDilate) + "  compress " + string$(nCompress) + "  granulate " + string$(nGranulate) + "  retrograde " + string$(nRetro) + "  ostinato " + string$(nOstinato) + "  |  close calls " + string$(closeCalls)

    Font size: 10
    Colour: "Black"
    Line width: 1

    removeObject: vizSrc
endif

# ============================================================
# STEP 8: REPORT AND CLEANUP
# ============================================================
writeInfoLine: "Fuzzy Time Re-Composer v0.4.0"
appendInfoLine: "=========================================================="
appendInfoLine: "source            : ", srcName$
appendInfoLine: "preset            : ", preset$
appendInfoLine: presetNote$
appendInfoLine: "channels          : ", nch, " -> ", outChannels, " (preserved)"
appendInfoLine: "analysis source   : ", analysisSource$
appendInfoLine: ""
appendInfoLine: "-- segmentation ------------------------------------------"
appendInfoLine: "mode              : ", segmentModeName$
appendInfoLine: "target length     : ", fixed$(segment_length_ms, 1), " ms"
appendInfoLine: "segments found    : ", nSeg
if nSeg >= maxSeg
    appendInfoLine: "WARNING           : segment cap (", maxSeg, ") reached; later material was"
    appendInfoLine: "                    absorbed into the final segment."
endif
appendInfoLine: "mean seg duration : ", fixed$(dur / nSeg * 1000, 1), " ms"
appendInfoLine: ""
appendInfoLine: "-- fuzzy inference ---------------------------------------"
appendInfoLine: "sensitivity       : ", fixed$(fuzzy_sensitivity, 2),
    ... "  (membership ramp ", fixed$(muLo, 2), " -> ", fixed$(muHi, 2), ")"
appendInfoLine: "NOTE              : descriptors are normalised across this file's"
appendInfoLine: "                    segments, so memberships are relative to this"
appendInfoLine: "                    material and are not comparable between files."
appendInfoLine: "mean activation   : preserve ", fixed$(sumA1 / nSeg, 3),
    ... "  dilate ", fixed$(sumA2 / nSeg, 3), "  compress ", fixed$(sumA3 / nSeg, 3)
appendInfoLine: "                    granulate ", fixed$(sumA4 / nSeg, 3),
    ... "  retrograde ", fixed$(sumA5 / nSeg, 3), "  ostinato ", fixed$(sumA6 / nSeg, 3)
appendInfoLine: "                    (the gesture is the argmax of these six; a rule that never"
appendInfoLine: "                    wins usually needs a higher bias or Fuzzy_sensitivity)"
appendInfoLine: "gesture census    : preserve ", nPreserve, "  dilate ", nDilate,
    ... "  compress ", nCompress
appendInfoLine: "                    granulate ", nGranulate, "  retrograde ", nRetro,
    ... "  ostinato ", nOstinato
appendInfoLine: "close calls       : ", closeCalls, " of ", nSeg,
    ... "  (winning rule led the runner-up by less than ",
    ... fixed$(closeCallLimit * 100, 0), "%; drawn as rings in the decision map)"
appendInfoLine: ""
appendInfoLine: "-- time warping ------------------------------------------"
appendInfoLine: "requested range   : ", fixed$(max_compression, 3), "x .. ", fixed$(max_dilation, 3), "x"
appendInfoLine: "achieved factors  : ", fixed$(minWarp, 3), "x .. ", fixed$(maxWarp, 3),
    ... "x   (mean ", fixed$(meanWarp, 3), "x)"
appendInfoLine: "segments warped   : ", warpApplied
appendInfoLine: "max PSOLA passes  : ", maxWarpPasses
appendInfoLine: "left unwarped     : ", warpSkipped, "  (shorter than ",
    ... fixed$(minWarpDur * 1000, 1), " ms = 4 / Pitch_floor; PSOLA needs the pitch analysis)"
if warpClampedPasses > 0
    appendInfoLine: "chained passes    : ", warpClampedPasses, " (a single Lengthen pass is clamped to"
    appendInfoLine: "                    0.25x-3.0x, so larger factors are applied in stages)"
endif
appendInfoLine: ""
appendInfoLine: "-- re-composition ----------------------------------------"
appendInfoLine: "reorder mode      : ", reorderModeName$
appendInfoLine: "trajectory        : ", trajectoryName$
appendInfoLine: "grains placed     : ", nGrain
if grainCapHit
    appendInfoLine: "WARNING           : grain cap (", maxGrain, ") reached; some grains were dropped."
    appendInfoLine: "                    Raise Micro_grain_ms or lower Fragmentation."
endif
appendInfoLine: "crossfade law     : ", crossfade_law$
appendInfoLine: "crossfade range   : ", fixed$(fade_min_ms, 1), " - ", fixed$(fade_max_ms, 1),
    ... " ms, scaled by mu_Sustain"
appendInfoLine: "assembly          : buffer write at sample-aligned offsets (Concatenate is"
appendInfoLine: "                    NOT used, so object-list order cannot reorder the audio)"
appendInfoLine: "seed              : ", seedUsed
if random_seed = 0
    appendInfoLine: "                    (generated unpredictably; copy this seed to reproduce the run)"
endif
appendInfoLine: ""
appendInfoLine: "-- output ------------------------------------------------"
appendInfoLine: "duration          : ", fixed$(dur, 3), " s -> ", fixed$(outDur, 3), " s  (",
    ... fixed$(outDur / dur, 3), "x)"
appendInfoLine: "peak              : ", fixed$(peakRaw, 4), " -> ", fixed$(peakFinal, 4)
if gainApplied < 1
    appendInfoLine: "safety            : attenuate-only, ", fixed$(20 * log10(gainApplied), 2),
        ... " dB applied to reach ", fixed$(safety_peak, 3)
elsif safety_peak = 0
    appendInfoLine: "safety            : disabled"
else
    appendInfoLine: "safety            : peak already below ", fixed$(safety_peak, 3),
        ... "; no gain change"
endif
appendInfoLine: "object            : Sound ", outName$
appendInfoLine: "=========================================================="

removeObject: snd, srcProc, intGlobal, pitchGlobal, harmGlobal

random_initializeSafelyAndUnpredictably()

selectObject: result
if play_result
    Play
endif
