# ============================================================
# Praat AudioTools - Accelerating Polyrhythm.praat
# Author: Shai Cohen
# Affiliation: Department of Music, Bar-Ilan University, Israel
# Email: shai.cohen@biu.ac.il
# Version: 0.4 reviewed (2026)
# License: MIT License
# Repository: https://github.com/ShaiCohen-ops/Praat-plugin_AudioTools
#
# Description:
#   Accelerating Polyrhythm Generator
#   Creates evolving polyrhythmic patterns whose cycle speed moves
#   from 1x at the beginning to Acceleration_factor at the end.
#
# Review changes v0.4:
#   - Corrected acceleration semantics. Acceleration_factor is now the
#     TOTAL start-to-end speed ratio, not a multiplier applied again
#     on every cycle. This prevents late-cycle collapse to sub-ms clicks.
#   - Exponential mode: speed(c) = a^p.
#     Linear mode:      speed(c) = 1 + (a - 1) p.
#     where p=(cycle-1)/(total_cycles-1).
#   - Target duration back-calculation updated to the same law.
#   - Added robust parameter guards and a minimum renderable tone length.
#   - Added reproducible Random_seed for Random evolution.
#   - "3:2:4 Triple layer" now really renders three rhythmic layers.
#   - Reich preset now applies an explicit one-beat phase cycle to P2
#     instead of leaving two identical 12-beat grids permanently aligned.
#   - Replaced unsafe dynamic Sound-name access with object(id,x,channel).
#   - Triangle and square are finite band-limited harmonic approximations;
#     Pluck omits harmonics above the Nyquist guard.
#   - Visualization uses actual cycle/event values generated by the DSP.
#   - IOI panel reflects Rhythm morph and the true third layer.
#   - Adaptive morph panel shows the selected transformation itself.
#   - Picture layout follows the Praat AudioTools research house style.
# ============================================================

form Accelerating Polyrhythm Generator
    comment === Preset ===
    optionmenu Preset 1
        option Custom (use settings below)
        option 3:2 Hemiola (gentle)
        option 4:3 Cross-rhythm
        option 5:4 Quintuplet feel
        option 7:4 Progressive rock
        option 5:3 Bell-like cross-rhythm
        option 8:5 Golden-ratio approximation
        option 3:2:4 Triple layer
        option Nancarrow Study 21 inspired
        option Reich-inspired phase drift
        option Ligeti Etude feel

    comment === Duration: Target overrides initial cycle duration if > 0 ===
    positive Base_duration_s 2.0
    real Target_total_duration_s 0
    natural Total_cycles 8

    comment === Patterns: beats per cycle / tone frequency ===
    natural Pattern1_beats 3
    positive Pattern1_frequency_Hz 300
    natural Pattern2_beats 4
    positive Pattern2_frequency_Hz 500

    comment === Acceleration: final speed relative to first cycle ===
    positive Acceleration_factor 2.0
    boolean Exponential_acceleration 1

    comment === Morphing ===
    optionmenu Morph_type 1
        option None
        option Frequency morph
        option Amplitude morph
        option Rhythm morph
        option Pan morph
        option Random evolution

    comment === Tone Shape ===
    positive Max_tone_duration_ms 100
    real Attack_ms 5
    real Decay_ms 30
    optionmenu Waveform 1
        option Sine
        option Triangle (band-limited)
        option Square (band-limited)
        option Pluck (decaying harmonics)

    comment === Reproducibility ===
    integer Random_seed 0
    comment 0 = unpredictable; positive value = reproducible Random evolution

    comment === Output ===
    boolean Play_result 1
    boolean Draw_visualization 1
endform

# ---------------------------------------------------------------------------
# 0. PRESET CONFIGURATION
# ---------------------------------------------------------------------------

# Preset initial-cycle durations were retuned so the corrected start-to-end
# acceleration law keeps approximately the familiar total length of v0.3 presets.

# Hidden defaults.
sample_rate_Hz = 44100
pattern1_amplitude = 0.4
pattern1_pan = -0.5
pattern2_amplitude = 0.4
pattern2_pan = 0.5

useThirdPattern = 0
pattern3_beats = 0
pattern3_frequency_Hz = 523.25
pattern3_amplitude = 0.34
pattern3_pan = 0.0

# Special phase-cycle flag used by the Reich-inspired preset.
usePhaseDrift = 0

if preset = 2
    # 3:2 Hemiola (gentle)
    pattern1_beats = 3
    pattern2_beats = 2
    pattern1_frequency_Hz = 440
    pattern2_frequency_Hz = 554.37
    base_duration_s = 1.107
    total_cycles = 6
    acceleration_factor = 1.5
    exponential_acceleration = 1
    morph_type = 1
    waveform = 1

elsif preset = 3
    # 4:3 Cross-rhythm
    pattern1_beats = 4
    pattern2_beats = 3
    pattern1_frequency_Hz = 330
    pattern2_frequency_Hz = 440
    base_duration_s = 0.687
    total_cycles = 8
    acceleration_factor = 2.0
    exponential_acceleration = 1
    morph_type = 1
    waveform = 1

elsif preset = 4
    # 5:4 Quintuplet feel
    pattern1_beats = 5
    pattern2_beats = 4
    pattern1_frequency_Hz = 392
    pattern2_frequency_Hz = 523.25
    base_duration_s = 0.858
    total_cycles = 8
    acceleration_factor = 2.0
    exponential_acceleration = 1
    morph_type = 2
    waveform = 1

elsif preset = 5
    # 7:4 Progressive rock
    pattern1_beats = 7
    pattern2_beats = 4
    pattern1_frequency_Hz = 220
    pattern2_frequency_Hz = 440
    base_duration_s = 1.340
    total_cycles = 6
    acceleration_factor = 1.8
    exponential_acceleration = 1
    morph_type = 1
    waveform = 3

elsif preset = 6
    # 5:3 bell-like cross-rhythm. The old title "African bell pattern"
    # overclaimed a specific style while rendering only evenly spaced grids.
    pattern1_beats = 5
    pattern2_beats = 3
    pattern1_frequency_Hz = 800
    pattern2_frequency_Hz = 1200
    base_duration_s = 0.379
    total_cycles = 10
    acceleration_factor = 2.5
    exponential_acceleration = 1
    morph_type = 5
    waveform = 4
    max_tone_duration_ms = 60
    attack_ms = 2
    decay_ms = 50

elsif preset = 7
    # 8:5 ratio; acceleration itself follows phi.
    pattern1_beats = 8
    pattern2_beats = 5
    pattern1_frequency_Hz = 261.63
    pattern2_frequency_Hz = 392
    base_duration_s = 1.207
    total_cycles = 8
    acceleration_factor = 1.618
    exponential_acceleration = 1
    morph_type = 2
    waveform = 1

elsif preset = 8
    # TRUE 3:2:4 triple layer.
    pattern1_beats = 3
    pattern2_beats = 2
    pattern1_frequency_Hz = 262
    pattern2_frequency_Hz = 392
    pattern1_pan = -0.65
    pattern2_pan = 0.65

    useThirdPattern = 1
    pattern3_beats = 4
    pattern3_frequency_Hz = 523.25
    pattern3_amplitude = 0.32
    pattern3_pan = 0.0

    base_duration_s = 0.460
    total_cycles = 12
    acceleration_factor = 2.0
    exponential_acceleration = 1
    morph_type = 6
    waveform = 1

elsif preset = 9
    # Nancarrow Study 21 inspired: close 17:18 strata and mild global acceleration.
    pattern1_beats = 17
    pattern2_beats = 18
    pattern1_frequency_Hz = 220
    pattern2_frequency_Hz = 233.08
    base_duration_s = 3.577
    total_cycles = 6
    acceleration_factor = 1.06
    exponential_acceleration = 1
    morph_type = 1
    waveform = 4
    max_tone_duration_ms = 80

elsif preset = 10
    # Reich-inspired: equal 12-pulse grids, with P2 moving through
    # one complete beat of phase offset over the piece.
    pattern1_beats = 12
    pattern2_beats = 12
    pattern1_frequency_Hz = 330
    pattern2_frequency_Hz = 440
    base_duration_s = 2.740
    total_cycles = 12
    acceleration_factor = 1.02
    exponential_acceleration = 0
    morph_type = 1
    waveform = 1
    usePhaseDrift = 1

elsif preset = 11
    # Ligeti-Etude-like fast 5:7 cross-rhythm.
    pattern1_beats = 5
    pattern2_beats = 7
    pattern1_frequency_Hz = 440
    pattern2_frequency_Hz = 554.37
    base_duration_s = 0.527
    total_cycles = 10
    acceleration_factor = 2.2
    exponential_acceleration = 1
    morph_type = 4
    waveform = 1
    attack_ms = 3
    decay_ms = 40
endif

# ---------------------------------------------------------------------------
# 1. PARAMETER GUARDS
# ---------------------------------------------------------------------------

if target_total_duration_s < 0
    target_total_duration_s = 0
endif

if total_cycles < 1
    total_cycles = 1
endif
if total_cycles > 1000
    exitScript: "Total cycles are limited to 1000."
endif

if pattern1_beats < 1
    pattern1_beats = 1
endif
if pattern2_beats < 1
    pattern2_beats = 1
endif
if pattern1_beats > 1000 or pattern2_beats > 1000
    exitScript: "Pattern beat counts are limited to 1000 per cycle."
endif

if pattern1_frequency_Hz <= 0 or pattern2_frequency_Hz <= 0
    exitScript: "Pattern frequencies must be positive."
endif

if acceleration_factor <= 0
    exitScript: "Acceleration factor must be greater than zero."
endif

if max_tone_duration_ms <= 0
    exitScript: "Maximum tone duration must be greater than zero."
endif

if attack_ms < 0
    attack_ms = 0
endif
if decay_ms < 0
    decay_ms = 0
endif

if random_seed < 0
    random_seed = 0
endif

nyquistGuard = 0.48 * sample_rate_Hz

# The finite harmonic waveforms omit partials above the guard, but the
# fundamental itself must remain renderable.
if pattern1_frequency_Hz >= nyquistGuard or pattern2_frequency_Hz >= nyquistGuard
    exitScript: "Pattern fundamental frequency must remain below 0.48 times the sample rate."
endif
if useThirdPattern = 1 and pattern3_frequency_Hz >= nyquistGuard
    exitScript: "Pattern 3 fundamental frequency must remain below 0.48 times the sample rate."
endif

# ---------------------------------------------------------------------------
# 2. ACCELERATION LAW / TARGET-DURATION SOLUTION
# ---------------------------------------------------------------------------

# Acceleration_factor now means end-speed / start-speed.
# p runs from 0 at cycle 1 to 1 at the final cycle.
durationWeightSum = 0

for cycle to total_cycles
    if total_cycles = 1
        progress = 0
    else
        progress = (cycle - 1) / (total_cycles - 1)
    endif

    if exponential_acceleration
        speedFactor = acceleration_factor ^ progress
    else
        speedFactor = 1 + (acceleration_factor - 1) * progress
    endif

    if speedFactor <= 0
        exitScript: "The selected acceleration law produced a non-positive speed."
    endif

    durationWeightSum += 1 / speedFactor
endfor

if target_total_duration_s > 0
    base_duration_s = target_total_duration_s / durationWeightSum
endif

if base_duration_s <= 0
    exitScript: "Initial cycle duration must be greater than zero."
endif

# ---------------------------------------------------------------------------
# 3. RANDOM STATE / UNIQUE OBJECT SUFFIX
# ---------------------------------------------------------------------------

# Generate a unique suffix before optional predictable seeding.
uid$ = string$(randomInteger(10000, 99999))

usesRandom = (morph_type = 6)
if usesRandom
    if random_seed = 0
        random_initializeSafelyAndUnpredictably ()
        seedText$ = "unseeded"
    else
        random_initializeWithSeedUnsafelyButPredictably (random_seed)
        seedText$ = "seed " + string$(random_seed)
    endif
else
    seedText$ = "deterministic"
endif

# ---------------------------------------------------------------------------
# 4. PRE-CALCULATE CYCLES AND ACTUAL EVENTS
# ---------------------------------------------------------------------------

twoPi = 2 * pi

cycleStart# = zero#(total_cycles)
cycleDur# = zero#(total_cycles)
cycleSpeed# = zero#(total_cycles)

cycleBeats1# = zero#(total_cycles)
cycleBeats2# = zero#(total_cycles)
cycleBeats3# = zero#(total_cycles)

cycleFreq1# = zero#(total_cycles)
cycleFreq2# = zero#(total_cycles)
cycleFreq3# = zero#(total_cycles)

cycleAmp1# = zero#(total_cycles)
cycleAmp2# = zero#(total_cycles)
cycleAmp3# = zero#(total_cycles)

cyclePan1# = zero#(total_cycles)
cyclePan2# = zero#(total_cycles)
cyclePan3# = zero#(total_cycles)

cycleIOI1# = zero#(total_cycles)
cycleIOI2# = zero#(total_cycles)
cycleIOI3# = zero#(total_cycles)
cyclePhase2# = zero#(total_cycles)

# +20 per cycle safely covers the +4 Rhythm morph and the optional third layer.
maxEvents = total_cycles * (pattern1_beats + pattern2_beats + pattern3_beats + 20)
eventTime# = zero#(maxEvents)
eventFreq# = zero#(maxEvents)
eventAmp# = zero#(maxEvents)
eventPan# = zero#(maxEvents)
eventDur# = zero#(maxEvents)
eventPattern# = zero#(maxEvents)

nEvents = 0
currentTime = 0
minimumToneSamples = 6

for cycle to total_cycles
    if total_cycles = 1
        morphProgress = 0
    else
        morphProgress = (cycle - 1) / (total_cycles - 1)
    endif

    if exponential_acceleration
        speedFactor = acceleration_factor ^ morphProgress
    else
        speedFactor = 1 + (acceleration_factor - 1) * morphProgress
    endif

    cycleDuration = base_duration_s / speedFactor

    # Start with base pattern values.
    freq1 = pattern1_frequency_Hz
    freq2 = pattern2_frequency_Hz
    freq3 = pattern3_frequency_Hz

    amp1 = pattern1_amplitude
    amp2 = pattern2_amplitude
    amp3 = pattern3_amplitude

    pan1 = pattern1_pan
    pan2 = pattern2_pan
    pan3 = pattern3_pan

    beats1 = pattern1_beats
    beats2 = pattern2_beats
    beats3 = pattern3_beats

    # Apply one morph state per cycle; values are stored and reused by the figure.
    if morph_type = 2
        # Frequency morph: voices converge.
        freq1 = pattern1_frequency_Hz * (1 + 0.5 * morphProgress)
        freq2 = pattern2_frequency_Hz * (1 - 0.25 * morphProgress)
        if useThirdPattern
            freq3 = pattern3_frequency_Hz * (1 - 0.10 * morphProgress)
        endif

    elsif morph_type = 3
        # Amplitude morph: crossfade.
        amp1 = pattern1_amplitude * (1 - 0.5 * morphProgress)
        amp2 = pattern2_amplitude * (0.5 + 0.5 * morphProgress)
        if useThirdPattern
            amp3 = pattern3_amplitude
        endif

    elsif morph_type = 4
        # Rhythm morph: P1 gains up to four beats.
        beats1 = pattern1_beats + round(morphProgress * 4)

    elsif morph_type = 5
        # Pan morph: outer voices swap sides.
        pan1 = pattern1_pan + (pattern2_pan - pattern1_pan) * morphProgress
        pan2 = pattern2_pan + (pattern1_pan - pattern2_pan) * morphProgress

    elsif morph_type = 6
        # Random evolution. One realization is generated here and stored.
        freq1 = pattern1_frequency_Hz * randomUniform(0.8, 1.2)
        freq2 = pattern2_frequency_Hz * randomUniform(0.8, 1.2)
        amp1 = pattern1_amplitude * randomUniform(0.6, 1.0)
        amp2 = pattern2_amplitude * randomUniform(0.6, 1.0)
        pan1 = pattern1_pan + randomUniform(-0.3, 0.3)
        pan2 = pattern2_pan + randomUniform(-0.3, 0.3)

        if useThirdPattern
            freq3 = pattern3_frequency_Hz * randomUniform(0.8, 1.2)
            amp3 = pattern3_amplitude * randomUniform(0.6, 1.0)
            pan3 = pattern3_pan + randomUniform(-0.3, 0.3)
        endif
    endif

    # Fundamental-frequency guard after morphing/randomization.
    if freq1 >= nyquistGuard or freq2 >= nyquistGuard
        if usesRandom and random_seed <> 0
            random_initializeSafelyAndUnpredictably ()
        endif
        exitScript: "A morphed/randomized fundamental reached the Nyquist safety guard. Lower the pattern frequencies."
    endif
    if useThirdPattern and freq3 >= nyquistGuard
        if usesRandom and random_seed <> 0
            random_initializeSafelyAndUnpredictably ()
        endif
        exitScript: "Pattern 3 reached the Nyquist safety guard. Lower its frequency."
    endif

    # Keep panning in the constant-power domain.
    pan1 = min(1, max(-1, pan1))
    pan2 = min(1, max(-1, pan2))
    pan3 = min(1, max(-1, pan3))

    spacing1 = cycleDuration / beats1
    spacing2 = cycleDuration / beats2

    if useThirdPattern
        spacing3 = cycleDuration / beats3
        smallestSpacing = min(spacing1, min(spacing2, spacing3))
    else
        spacing3 = 0
        smallestSpacing = min(spacing1, spacing2)
    endif

    # Limit tone duration to 80 percent of the tightest rhythmic spacing.
    maxToneThisCycle = 0.8 * smallestSpacing
    toneDur = min(max_tone_duration_ms / 1000, maxToneThisCycle)

    if toneDur * sample_rate_Hz < minimumToneSamples
        if usesRandom and random_seed <> 0
            random_initializeSafelyAndUnpredictably ()
        endif
        exitScript: "Acceleration/target duration makes tones shorter than six samples. Increase duration or reduce acceleration."
    endif

    # Store ACTUAL cycle state.
    cycleStart#[cycle] = currentTime
    cycleDur#[cycle] = cycleDuration
    cycleSpeed#[cycle] = speedFactor

    cycleBeats1#[cycle] = beats1
    cycleBeats2#[cycle] = beats2
    cycleBeats3#[cycle] = beats3

    cycleFreq1#[cycle] = freq1
    cycleFreq2#[cycle] = freq2
    cycleFreq3#[cycle] = freq3

    cycleAmp1#[cycle] = amp1
    cycleAmp2#[cycle] = amp2
    cycleAmp3#[cycle] = amp3

    cyclePan1#[cycle] = pan1
    cyclePan2#[cycle] = pan2
    cyclePan3#[cycle] = pan3

    cycleIOI1#[cycle] = spacing1
    cycleIOI2#[cycle] = spacing2
    cycleIOI3#[cycle] = spacing3

    # Reich-inspired P2 phase cycle: move from 0 to one complete beat.
    if usePhaseDrift
        phaseOffset = morphProgress * spacing2
    else
        phaseOffset = 0
    endif
    cyclePhase2#[cycle] = if spacing2 > 0 then phaseOffset / spacing2 else 0 fi

    # Pattern 1 events.
    for idx to beats1
        nEvents += 1
        eventTime#[nEvents] = currentTime + (idx - 1) * spacing1
        eventFreq#[nEvents] = freq1
        eventAmp#[nEvents] = amp1
        eventPan#[nEvents] = pan1
        eventDur#[nEvents] = toneDur
        eventPattern#[nEvents] = 1
    endfor

    # Pattern 2 events, optionally phase-shifted within the cycle.
    for idx to beats2
        localTime = (idx - 1) * spacing2 + phaseOffset
        localTime = localTime - floor(localTime / cycleDuration) * cycleDuration

        nEvents += 1
        eventTime#[nEvents] = currentTime + localTime
        eventFreq#[nEvents] = freq2
        eventAmp#[nEvents] = amp2
        eventPan#[nEvents] = pan2
        eventDur#[nEvents] = toneDur
        eventPattern#[nEvents] = 2
    endfor

    # True third layer for preset 8.
    if useThirdPattern
        for idx to beats3
            nEvents += 1
            eventTime#[nEvents] = currentTime + (idx - 1) * spacing3
            eventFreq#[nEvents] = freq3
            eventAmp#[nEvents] = amp3
            eventPan#[nEvents] = pan3
            eventDur#[nEvents] = toneDur
            eventPattern#[nEvents] = 3
        endfor
    endif

    currentTime += cycleDuration
endfor

totalDuration = currentTime

# Restore unpredictable global RNG after reproducible event generation.
if usesRandom and random_seed <> 0
    random_initializeSafelyAndUnpredictably ()
endif

# ---------------------------------------------------------------------------
# 5. INFO
# ---------------------------------------------------------------------------

writeInfoLine: "=== Accelerating Polyrhythm Generator v0.4 ==="
if preset > 1
    appendInfoLine: "Preset: ", preset$
endif

if useThirdPattern
    appendInfoLine: "Pattern: ", pattern1_beats, " : ", pattern2_beats, " : ", pattern3_beats
else
    appendInfoLine: "Pattern: ", pattern1_beats, " : ", pattern2_beats
endif

appendInfoLine: "Cycles: ", total_cycles
appendInfoLine: "Initial cycle: ", fixed$(base_duration_s, 4), " s"
appendInfoLine: "Final speed: ", fixed$(cycleSpeed#[total_cycles], 4), " x"
appendInfoLine: "Final cycle: ", fixed$(cycleDur#[total_cycles], 4), " s"
appendInfoLine: "Total duration: ", fixed$(totalDuration, 4), " s"
appendInfoLine: "Morph: ", morph_type$
appendInfoLine: "Random state: ", seedText$
if usePhaseDrift
    appendInfoLine: "P2 phase cycle: 0 -> 1 beat"
endif
appendInfoLine: "Generated events: ", nEvents
appendInfoLine: ""

# ---------------------------------------------------------------------------
# 6. AUDIO RENDERING
# ---------------------------------------------------------------------------

soundL = Create Sound from formula: "poly_L_" + uid$, 1, 0, totalDuration, sample_rate_Hz, "0"
soundR = Create Sound from formula: "poly_R_" + uid$, 1, 0, totalDuration, sample_rate_Hz, "0"

attackTime = attack_ms / 1000
decayTime = decay_ms / 1000

appendInfoLine: "Rendering audio..."

for evt to nEvents
    tStart = eventTime#[evt]
    freq = eventFreq#[evt]
    amp = eventAmp#[evt]
    pan = eventPan#[evt]
    dur = eventDur#[evt]

    # Constant-power panning.
    panAngle = (pan + 1) / 2 * (pi / 2)
    ampL = amp * cos(panAngle)
    ampR = amp * sin(panAngle)

    # Envelope adapts to the available event duration.
    actualAttack = min(attackTime, dur / 3)
    actualDecay = min(decayTime, dur / 2)
    sustainEnd = dur - actualDecay

    toneSound = Create Sound from formula: "tone_" + uid$, 1, 0, dur, sample_rate_Hz, "0"

    # Band-limited / guarded waveform generation.
    if waveform = 1
        Formula: "sin(twoPi * freq * x)"

    elsif waveform = 2
        # Finite triangle approximation: odd harmonics decay as 1/n^2.
        Formula: "(8/(pi^2)) * (sin(twoPi*freq*x) - if 3*freq < nyquistGuard then sin(twoPi*3*freq*x)/9 else 0 fi + if 5*freq < nyquistGuard then sin(twoPi*5*freq*x)/25 else 0 fi - if 7*freq < nyquistGuard then sin(twoPi*7*freq*x)/49 else 0 fi + if 9*freq < nyquistGuard then sin(twoPi*9*freq*x)/81 else 0 fi)"

    elsif waveform = 3
        # Finite square approximation: only odd partials below Nyquist guard.
        Formula: "(4/pi) * (sin(twoPi*freq*x) + if 3*freq < nyquistGuard then sin(twoPi*3*freq*x)/3 else 0 fi + if 5*freq < nyquistGuard then sin(twoPi*5*freq*x)/5 else 0 fi + if 7*freq < nyquistGuard then sin(twoPi*7*freq*x)/7 else 0 fi + if 9*freq < nyquistGuard then sin(twoPi*9*freq*x)/9 else 0 fi)"

    elsif waveform = 4
        # Decaying harmonics; omit any partial above the Nyquist guard.
        Formula: "sin(twoPi*freq*x) + if 2*freq < nyquistGuard then 0.5*sin(twoPi*2*freq*x)*exp(-x*10) else 0 fi + if 3*freq < nyquistGuard then 0.25*sin(twoPi*3*freq*x)*exp(-x*20) else 0 fi"
    endif

    selectObject: toneSound

    if actualAttack > 0
        Formula: "if x < actualAttack then self * (x / actualAttack) else self fi"
    endif

    if actualDecay > 0
        Formula: "if x > sustainEnd then self * max(0, (dur - x) / actualDecay) else self fi"
    endif

    Formula: "self * amp"

    # Mix by object ID, not by a dynamically constructed object name.
    toneIdStr$ = string$(toneSound)

    selectObject: soundL
    Formula: "if x >= tStart and x < tStart + dur then self + (ampL / amp) * object(" + toneIdStr$ + ", x - tStart, 1) else self fi"

    selectObject: soundR
    Formula: "if x >= tStart and x < tStart + dur then self + (ampR / amp) * object(" + toneIdStr$ + ", x - tStart, 1) else self fi"

    removeObject: toneSound

    if evt mod 40 = 0
        appendInfoLine: "  ", evt, " / ", nEvents, " events..."
    endif
endfor

# ---------------------------------------------------------------------------
# 7. STEREO OUTPUT / NORMALIZATION
# ---------------------------------------------------------------------------

selectObject: soundL, soundR
stereoSound = Combine to stereo

if useThirdPattern
    Rename: "AccelPoly_" + string$(pattern1_beats) + "v" + string$(pattern2_beats) + "v" + string$(pattern3_beats)
else
    Rename: "AccelPoly_" + string$(pattern1_beats) + "v" + string$(pattern2_beats)
endif

removeObject: soundL, soundR

# Deliberate whole-output normalization. This preserves all relative event,
# morph, and panning relationships while providing a consistent playback peak.
selectObject: stereoSound
Scale peak: 0.9

# ---------------------------------------------------------------------------
# 8. VISUALIZATION
# ---------------------------------------------------------------------------

if draw_visualization
    appendInfoLine: ""
    appendInfoLine: "Drawing visualization..."
    @drawRhythmVisualization: nEvents, totalDuration
endif

if play_result
    selectObject: stereoSound
    Play
endif

selectObject: stereoSound

appendInfoLine: ""
appendInfoLine: "=== Done ==="
appendInfoLine: "Created: ", selected$("Sound")


# ==============================================================================
# PROCEDURE: drawRhythmVisualization
# ==============================================================================
procedure drawRhythmVisualization: .nEvents, .totalDur

    Erase all

    # Restrained AudioTools palette.
    .col1$ = "{0.20, 0.42, 0.72}"
    .col2$ = "{0.78, 0.34, 0.24}"
    .col3$ = "{0.38, 0.62, 0.40}"
    .grid$ = "{0.84, 0.84, 0.84}"
    .bg$ = "{0.965, 0.965, 0.970}"
    .textGrey$ = "{0.35, 0.35, 0.40}"

    .leftViewport = 0.82
    .rightViewport = 7.72
    .cycleAxisMax = max(2, total_cycles)

    # ------------------------------------------------------------------
    # TITLE
    # ------------------------------------------------------------------
    Select inner viewport: 0.1, 7.9, 0.05, 0.34
    Axes: 0, 1, 0, 1
    Font size: 12
    Colour: "Black"
    Text: 0.5, "centre", 0.58, "half", "##Accelerating Polyrhythm##"

    Select inner viewport: 0.1, 7.9, 0.40, 0.60
    Axes: 0, 1, 0, 1
    Font size: 6
    Colour: .textGrey$

    if useThirdPattern
        .ratio$ = string$(pattern1_beats) + ":" + string$(pattern2_beats) + ":" + string$(pattern3_beats)
    else
        .ratio$ = string$(pattern1_beats) + ":" + string$(pattern2_beats)
    endif

    if exponential_acceleration
        .lawShort$ = "exp"
    else
        .lawShort$ = "linear"
    endif

    .subtitle$ = .ratio$ + " | " + string$(total_cycles) + " cycles | final speed " + fixed$(cycleSpeed#[total_cycles], 2) + "x | " + .lawShort$ + " | " + morph_type$
    Text: 0.5, "centre", 0.5, "half", .subtitle$

    # ------------------------------------------------------------------
    # PANEL A TITLE
    # ------------------------------------------------------------------
    Select inner viewport: 0.1, 7.9, 0.76, 1.00
    Axes: 0, 1, 0, 1
    Font size: 8
    Colour: "Black"
    Text: 0.5, "centre", 0.5, "half", "A  |  ACTUAL EVENT LATTICE"

    # ------------------------------------------------------------------
    # PANEL A DATA: actual event onset pattern
    # ------------------------------------------------------------------
    Select inner viewport: .leftViewport, .rightViewport, 1.06, 2.46

    if useThirdPattern
        .yMax = 3.5
        .y1 = 2.8
        .y2 = 1.8
        .y3 = 0.8
    else
        .yMax = 2.7
        .y1 = 2.0
        .y2 = 0.8
        .y3 = 0
    endif

    Axes: 0, .totalDur, 0, .yMax
    Paint rectangle: .bg$, 0, .totalDur, 0, .yMax

    # Cycle boundaries from the actual generated cycle array.
    Colour: .grid$
    Dotted line
    for .cycle from 2 to total_cycles
        .ct = cycleStart#[.cycle]
        Draw line: .ct, 0, .ct, .yMax
    endfor
    Plain line

    # Baselines.
    Colour: "{0.76, 0.76, 0.78}"
    Draw line: 0, .y1, .totalDur, .y1
    Draw line: 0, .y2, .totalDur, .y2
    if useThirdPattern
        Draw line: 0, .y3, .totalDur, .y3
    endif

    # Event stems: height shows actual event amplitude; x is actual onset.
    Line width: 1.5
    for .evt to .nEvents
        .t = eventTime#[.evt]
        .pat = eventPattern#[.evt]
        .a = eventAmp#[.evt]

        if .pat = 1
            .y = .y1
            Colour: .col1$
        elsif .pat = 2
            .y = .y2
            Colour: .col2$
        else
            .y = .y3
            Colour: .col3$
        endif

        .stem = 0.20 + 0.55 * min(1, .a / 0.4)
        Draw line: .t, .y - .stem/2, .t, .y + .stem/2
    endfor
    Line width: 1

    Colour: "Black"
    Draw inner box

    # After Draw inner box, explicitly restore data viewport/axes.
    Select inner viewport: .leftViewport, .rightViewport, 1.06, 2.46
    Axes: 0, .totalDur, 0, .yMax
    Marks bottom: 5, "yes", "yes", "no"

    # Row labels in an independent text strip.
    Select inner viewport: 0.16, 0.72, 1.06, 2.46
    Axes: 0, 1, 0, .yMax
    Font size: 6
    Colour: .col1$
    Text: 0.92, "right", .y1, "half", "P1"
    Colour: .col2$
    Text: 0.92, "right", .y2, "half", "P2"
    if useThirdPattern
        Colour: .col3$
        Text: 0.92, "right", .y3, "half", "P3"
    endif

    # ------------------------------------------------------------------
    # PANEL B TITLE
    # ------------------------------------------------------------------
    Select inner viewport: 0.1, 7.9, 2.72, 2.96
    Axes: 0, 1, 0, 1
    Font size: 8
    Colour: "Black"
    Text: 0.5, "centre", 0.5, "half", "B  |  ACTUAL INTER-ONSET INTERVAL BY CYCLE"

    # ------------------------------------------------------------------
    # PANEL B DATA: actual IOI values, including Rhythm morph
    # ------------------------------------------------------------------
    .maxIOI = 0
    for .cycle to total_cycles
        .maxIOI = max(.maxIOI, cycleIOI1#[.cycle])
        .maxIOI = max(.maxIOI, cycleIOI2#[.cycle])
        if useThirdPattern
            .maxIOI = max(.maxIOI, cycleIOI3#[.cycle])
        endif
    endfor
    .maxIOIms = 1000 * .maxIOI

    Select inner viewport: .leftViewport, .rightViewport, 3.02, 4.42
    Axes: 0, .totalDur, 0, .maxIOIms * 1.10
    Paint rectangle: .bg$, 0, .totalDur, 0, .maxIOIms * 1.10

    Line width: 1.5
    for .cycle to total_cycles
        .x1 = cycleStart#[.cycle]
        .x2 = .x1 + cycleDur#[.cycle]

        Colour: .col1$
        Draw line: .x1, 1000*cycleIOI1#[.cycle], .x2, 1000*cycleIOI1#[.cycle]

        Colour: .col2$
        Draw line: .x1, 1000*cycleIOI2#[.cycle], .x2, 1000*cycleIOI2#[.cycle]

        if useThirdPattern
            Colour: .col3$
            Draw line: .x1, 1000*cycleIOI3#[.cycle], .x2, 1000*cycleIOI3#[.cycle]
        endif
    endfor
    Line width: 1

    Colour: "Black"
    Draw inner box

    Select inner viewport: .leftViewport, .rightViewport, 3.02, 4.42
    Axes: 0, .totalDur, 0, .maxIOIms * 1.10
    Marks left: 4, "yes", "yes", "no"
    Marks bottom: 5, "yes", "yes", "no"
    Text left: "yes", "IOI (ms)"
    Text bottom: "yes", "Time (s)"

    # Compact manual legend.
    Select inner viewport: 5.72, 7.58, 3.10, 3.32
    Axes: 0, 1, 0, 1
    Font size: 5
    Colour: .col1$
    Text: 0.02, "left", 0.5, "half", "P1"
    Colour: .col2$
    Text: 0.34, "left", 0.5, "half", "P2"
    if useThirdPattern
        Colour: .col3$
        Text: 0.66, "left", 0.5, "half", "P3"
    endif

    # ------------------------------------------------------------------
    # PANEL C TITLE
    # ------------------------------------------------------------------
    Select inner viewport: 0.1, 7.9, 4.68, 4.92
    Axes: 0, 1, 0, 1
    Font size: 8
    Colour: "Black"

    if usePhaseDrift
        .panelCtitle$ = "C  |  PHASE TRAJECTORY - P2 OFFSET"
    elsif morph_type = 2
        .panelCtitle$ = "C  |  FREQUENCY MORPH - ACTUAL CYCLE VALUES"
    elsif morph_type = 3
        .panelCtitle$ = "C  |  AMPLITUDE MORPH - ACTUAL CYCLE VALUES"
    elsif morph_type = 4
        .panelCtitle$ = "C  |  RHYTHM MORPH - BEATS PER CYCLE"
    elsif morph_type = 5
        .panelCtitle$ = "C  |  PAN MORPH - ACTUAL CYCLE VALUES"
    elsif morph_type = 6
        .panelCtitle$ = "C  |  RANDOM EVOLUTION - ACTUAL FREQUENCY REALIZATION"
    else
        .panelCtitle$ = "C  |  ACCELERATION LAW - ACTUAL SPEED FACTOR"
    endif

    Text: 0.5, "centre", 0.5, "half", .panelCtitle$

    # ------------------------------------------------------------------
    # PANEL C DATA: adaptive mechanism view
    # ------------------------------------------------------------------
    Select inner viewport: .leftViewport, .rightViewport, 4.98, 6.38

    if usePhaseDrift
        .yMin = 0
        .yMaxC = 1.08
        Axes: 1, .cycleAxisMax, .yMin, .yMaxC
        Paint rectangle: .bg$, 1, .cycleAxisMax, .yMin, .yMaxC

        Colour: .col2$
        Line width: 1.5
        for .cycle from 1 to total_cycles - 1
            Draw line: .cycle, cyclePhase2#[.cycle], .cycle + 1, cyclePhase2#[.cycle + 1]
        endfor
        Line width: 1

        Colour: "Black"
        Draw inner box
        Select inner viewport: .leftViewport, .rightViewport, 4.98, 6.38
        Axes: 1, .cycleAxisMax, .yMin, .yMaxC
        Marks left: 3, "yes", "yes", "no"
        Marks bottom: min(total_cycles, 6), "yes", "yes", "no"
        Text left: "yes", "Offset (beats)"

    elsif morph_type = 2 or morph_type = 6
        .fMin = cycleFreq1#[1]
        .fMax = cycleFreq1#[1]
        for .cycle to total_cycles
            .fMin = min(.fMin, cycleFreq1#[.cycle])
            .fMin = min(.fMin, cycleFreq2#[.cycle])
            .fMax = max(.fMax, cycleFreq1#[.cycle])
            .fMax = max(.fMax, cycleFreq2#[.cycle])
            if useThirdPattern
                .fMin = min(.fMin, cycleFreq3#[.cycle])
                .fMax = max(.fMax, cycleFreq3#[.cycle])
            endif
        endfor
        .fPad = max(10, 0.08 * (.fMax - .fMin + 1))

        Axes: 1, .cycleAxisMax, .fMin - .fPad, .fMax + .fPad
        Paint rectangle: .bg$, 1, .cycleAxisMax, .fMin - .fPad, .fMax + .fPad

        Line width: 1.5
        for .cycle from 1 to total_cycles - 1
            Colour: .col1$
            Draw line: .cycle, cycleFreq1#[.cycle], .cycle+1, cycleFreq1#[.cycle+1]
            Colour: .col2$
            Draw line: .cycle, cycleFreq2#[.cycle], .cycle+1, cycleFreq2#[.cycle+1]
            if useThirdPattern
                Colour: .col3$
                Draw line: .cycle, cycleFreq3#[.cycle], .cycle+1, cycleFreq3#[.cycle+1]
            endif
        endfor
        Line width: 1

        Colour: "Black"
        Draw inner box
        Select inner viewport: .leftViewport, .rightViewport, 4.98, 6.38
        Axes: 1, .cycleAxisMax, .fMin - .fPad, .fMax + .fPad
        Marks left: 4, "yes", "yes", "no"
        Marks bottom: min(total_cycles, 6), "yes", "yes", "no"
        Text left: "yes", "Frequency (Hz)"

    elsif morph_type = 3
        .aMax = 0
        for .cycle to total_cycles
            .aMax = max(.aMax, cycleAmp1#[.cycle])
            .aMax = max(.aMax, cycleAmp2#[.cycle])
            if useThirdPattern
                .aMax = max(.aMax, cycleAmp3#[.cycle])
            endif
        endfor

        Axes: 1, .cycleAxisMax, 0, 1.12*.aMax
        Paint rectangle: .bg$, 1, .cycleAxisMax, 0, 1.12*.aMax

        Line width: 1.5
        for .cycle from 1 to total_cycles - 1
            Colour: .col1$
            Draw line: .cycle, cycleAmp1#[.cycle], .cycle+1, cycleAmp1#[.cycle+1]
            Colour: .col2$
            Draw line: .cycle, cycleAmp2#[.cycle], .cycle+1, cycleAmp2#[.cycle+1]
            if useThirdPattern
                Colour: .col3$
                Draw line: .cycle, cycleAmp3#[.cycle], .cycle+1, cycleAmp3#[.cycle+1]
            endif
        endfor
        Line width: 1

        Colour: "Black"
        Draw inner box
        Select inner viewport: .leftViewport, .rightViewport, 4.98, 6.38
        Axes: 1, .cycleAxisMax, 0, 1.12*.aMax
        Marks left: 4, "yes", "yes", "no"
        Marks bottom: min(total_cycles, 6), "yes", "yes", "no"
        Text left: "yes", "Amplitude"

    elsif morph_type = 4
        .bMax = 0
        for .cycle to total_cycles
            .bMax = max(.bMax, cycleBeats1#[.cycle])
            .bMax = max(.bMax, cycleBeats2#[.cycle])
            if useThirdPattern
                .bMax = max(.bMax, cycleBeats3#[.cycle])
            endif
        endfor

        Axes: 1, .cycleAxisMax, 0, .bMax + 1
        Paint rectangle: .bg$, 1, .cycleAxisMax, 0, .bMax + 1

        Line width: 1.5
        for .cycle from 1 to total_cycles - 1
            Colour: .col1$
            Draw line: .cycle, cycleBeats1#[.cycle], .cycle+1, cycleBeats1#[.cycle+1]
            Colour: .col2$
            Draw line: .cycle, cycleBeats2#[.cycle], .cycle+1, cycleBeats2#[.cycle+1]
            if useThirdPattern
                Colour: .col3$
                Draw line: .cycle, cycleBeats3#[.cycle], .cycle+1, cycleBeats3#[.cycle+1]
            endif
        endfor
        Line width: 1

        Colour: "Black"
        Draw inner box
        Select inner viewport: .leftViewport, .rightViewport, 4.98, 6.38
        Axes: 1, .cycleAxisMax, 0, .bMax + 1
        Marks left: min(.bMax + 1, 8), "yes", "yes", "no"
        Marks bottom: min(total_cycles, 6), "yes", "yes", "no"
        Text left: "yes", "Beats"

    elsif morph_type = 5
        Axes: 1, .cycleAxisMax, -1.05, 1.05
        Paint rectangle: .bg$, 1, .cycleAxisMax, -1.05, 1.05

        Colour: .grid$
        Draw line: 1, 0, .cycleAxisMax, 0

        Line width: 1.5
        for .cycle from 1 to total_cycles - 1
            Colour: .col1$
            Draw line: .cycle, cyclePan1#[.cycle], .cycle+1, cyclePan1#[.cycle+1]
            Colour: .col2$
            Draw line: .cycle, cyclePan2#[.cycle], .cycle+1, cyclePan2#[.cycle+1]
            if useThirdPattern
                Colour: .col3$
                Draw line: .cycle, cyclePan3#[.cycle], .cycle+1, cyclePan3#[.cycle+1]
            endif
        endfor
        Line width: 1

        Colour: "Black"
        Draw inner box
        Select inner viewport: .leftViewport, .rightViewport, 4.98, 6.38
        Axes: 1, .cycleAxisMax, -1.05, 1.05
        Marks left: 5, "yes", "yes", "no"
        Marks bottom: min(total_cycles, 6), "yes", "yes", "no"
        Text left: "yes", "Pan"

    else
        .speedMax = 0
        for .cycle to total_cycles
            .speedMax = max(.speedMax, cycleSpeed#[.cycle])
        endfor

        Axes: 1, .cycleAxisMax, 0, 1.10*.speedMax
        Paint rectangle: .bg$, 1, .cycleAxisMax, 0, 1.10*.speedMax

        Colour: "{0.30, 0.30, 0.35}"
        Line width: 1.5
        for .cycle from 1 to total_cycles - 1
            Draw line: .cycle, cycleSpeed#[.cycle], .cycle+1, cycleSpeed#[.cycle+1]
        endfor
        Line width: 1

        Colour: "Black"
        Draw inner box
        Select inner viewport: .leftViewport, .rightViewport, 4.98, 6.38
        Axes: 1, .cycleAxisMax, 0, 1.10*.speedMax
        Marks left: 4, "yes", "yes", "no"
        Marks bottom: min(total_cycles, 6), "yes", "yes", "no"
        Text left: "yes", "Speed factor"
    endif

    Text bottom: "yes", "Cycle"

    # ------------------------------------------------------------------
    # SUMMARY / MECHANISM BAR
    # ------------------------------------------------------------------
    Select inner viewport: 0.35, 7.65, 6.72, 7.52
    Axes: 0, 1, 0, 1
    Paint rectangle: "{0.945, 0.945, 0.950}", 0, 1, 0, 1

    Font size: 6
    Colour: "{0.30, 0.30, 0.34}"

    if exponential_acceleration
        .formula$ = "Speed = a^p ; cycle duration = T0 / speed ; p runs 0 to 1"
    else
        .formula$ = "Speed = 1 + (a - 1)p ; cycle duration = T0 / speed ; p runs 0 to 1"
    endif

    Text: 0.5, "centre", 0.74, "half", .formula$

    .ioiStart1 = 1000 * cycleIOI1#[1]
    .ioiEnd1 = 1000 * cycleIOI1#[total_cycles]
    .summary$ = "P1 IOI " + fixed$(.ioiStart1, 1) + " -> " + fixed$(.ioiEnd1, 1) + " ms | total " + fixed$(.totalDur, 2) + " s | " + string$(.nEvents) + " events | " + seedText$
    Text: 0.5, "centre", 0.25, "half", .summary$

    # Reset Picture state.
    Font size: 10
    Colour: "Black"
    Line width: 1
endproc
