# ============================================================
# Praat AudioTools - Algorithmic Metallic Synthesis.praat
# Author: Shai Cohen
# Affiliation: Department of Music, Bar-Ilan University, Israel
# Email: shai.cohen@biu.ac.il
# Version: 0.4 reviewed (2026)
# License: MIT License
# Repository: https://github.com/ShaiCohen-ops/Praat-plugin_AudioTools
#
# Description:
#   Algorithmic metallic synthesis built from regularly triggered
#   exponentially decaying FM ring kernels. Each voice has an inharmonic
#   carrier, a decaying modulation index, and an independent strike rate.
#   The pulse train is convolved with the ring kernel, so Resonance_decay_s
#   is a true per-strike decay constant and overlapping tails are preserved.
#
# Usage:
#   Run this script (no input sound required).
#
# Review changes v0.4:
#   - Replaced discontinuous duty-cycle gating with pulse-train convolution.
#   - Resonance_decay_s now controls each strike, not one global decay from t=0.
#   - Removed the misleading "filterQ": Hann-band third argument is smoothing
#     width in Hz, not resonance Q. Resonance is now generated by the ring kernel.
#   - Added sample-rate / Nyquist guards including FM sideband margin.
#   - Added reproducible Random_seed (0 = unpredictable).
#   - Replaced dynamic object-name Formula access with object IDs.
#   - Stereo Wide now uses short decorrelation delay; Rotating is equal-power.
#   - Visualization uses actual generated voice/event parameters and measured
#     output: strike map, waveform, spectrogram + model resonance guides.
# ============================================================

form Algorithmic Metallic Synthesis
    comment === Preset ===
    optionmenu Preset 1
        option Custom (use settings below)
        option Temple Bell
        option Gamelan
        option Industrial Clang
        option Wind Chimes
        option Gong Wash
        option Prepared Piano
        option Steel Drum

    comment === Basic Settings ===
    positive Duration_s 3
    integer Sample_rate_Hz 44100
    positive Base_frequency_Hz 200
    integer Number_of_voices 5
    integer Number_of_layers 3

    comment === Modulation / Resonance ===
    positive Modulation_rate_Hz 0.5
    real Modulation_depth 3.0
    positive Resonance_decay_s 0.1

    comment === Synthesis Mode ===
    optionmenu Synthesis_mode 1
        option Standard Metallic
        option Dense Shimmer
        option Sparse Bells
        option Rhythmic Clang
        option Chaotic Resonance

    comment === Output ===
    real Fade_time_s 0.5
    optionmenu Spatial_mode 1
        option Mono
        option Stereo Wide
        option Rotating
    boolean Randomize_parameters 1
    integer Random_seed 0
    boolean Normalize_output 1
    boolean Draw_visualization 1
    boolean Play_result 1
endform

# ============================================================================
# 1. Presets
# ============================================================================
preset_name$ = "Custom"

if preset = 2
    duration_s = 5
    base_frequency_Hz = 180
    number_of_voices = 6
    number_of_layers = 2
    modulation_rate_Hz = 0.3
    modulation_depth = 4.0
    resonance_decay_s = 0.8
    synthesis_mode = 3
    spatial_mode = 3
    fade_time_s = 1
    synthesis_mode$ = "Sparse Bells"
    preset_name$ = "Temple Bell"
elsif preset = 3
    duration_s = 4
    base_frequency_Hz = 250
    number_of_voices = 8
    number_of_layers = 3
    modulation_rate_Hz = 0.8
    modulation_depth = 2.5
    resonance_decay_s = 0.3
    synthesis_mode = 2
    spatial_mode = 2
    synthesis_mode$ = "Dense Shimmer"
    preset_name$ = "Gamelan"
elsif preset = 4
    duration_s = 3
    base_frequency_Hz = 120
    number_of_voices = 6
    number_of_layers = 4
    modulation_rate_Hz = 2.0
    modulation_depth = 5.0
    resonance_decay_s = 0.05
    synthesis_mode = 4
    spatial_mode = 2
    synthesis_mode$ = "Rhythmic Clang"
    preset_name$ = "Industrial Clang"
elsif preset = 5
    duration_s = 6
    base_frequency_Hz = 800
    number_of_voices = 10
    number_of_layers = 2
    modulation_rate_Hz = 0.2
    modulation_depth = 1.5
    resonance_decay_s = 0.4
    synthesis_mode = 3
    spatial_mode = 3
    randomize_parameters = 1
    synthesis_mode$ = "Sparse Bells"
    preset_name$ = "Wind Chimes"
elsif preset = 6
    duration_s = 8
    base_frequency_Hz = 80
    number_of_voices = 4
    number_of_layers = 3
    modulation_rate_Hz = 0.1
    modulation_depth = 6.0
    resonance_decay_s = 1.5
    synthesis_mode = 1
    spatial_mode = 3
    fade_time_s = 2
    synthesis_mode$ = "Standard Metallic"
    preset_name$ = "Gong Wash"
elsif preset = 7
    duration_s = 4
    base_frequency_Hz = 150
    number_of_voices = 6
    number_of_layers = 3
    modulation_rate_Hz = 1.5
    modulation_depth = 3.5
    resonance_decay_s = 0.15
    synthesis_mode = 5
    spatial_mode = 2
    synthesis_mode$ = "Chaotic Resonance"
    preset_name$ = "Prepared Piano"
elsif preset = 8
    duration_s = 3
    base_frequency_Hz = 300
    number_of_voices = 5
    number_of_layers = 2
    modulation_rate_Hz = 1.0
    modulation_depth = 2.0
    resonance_decay_s = 0.2
    synthesis_mode = 4
    spatial_mode = 1
    synthesis_mode$ = "Rhythmic Clang"
    preset_name$ = "Steel Drum"
endif

# ============================================================================
# 2. Validation and constants
# ============================================================================
if sample_rate_Hz < 8000
    exitScript: "Sample rate must be at least 8000 Hz."
endif
if number_of_voices < 1
    number_of_voices = 1
endif
if number_of_voices > 12
    number_of_voices = 12
endif
if number_of_layers < 1
    number_of_layers = 1
endif
if number_of_layers > 8
    number_of_layers = 8
endif
if modulation_rate_Hz <= 0
    modulation_rate_Hz = 0.01
endif
if resonance_decay_s <= 0
    resonance_decay_s = 0.01
endif
if fade_time_s < 0
    fade_time_s = 0
endif
if fade_time_s > duration_s / 2
    fade_time_s = duration_s / 2
endif
if random_seed < 0
    random_seed = 0
endif

# Dense mode doubles the requested voices per layer.
if synthesis_mode = 2
    estimatedVoices = number_of_layers * number_of_voices * 2
else
    estimatedVoices = number_of_layers * number_of_voices
endif
if estimatedVoices > 160
    exitScript: "Settings request more than 160 oscillator voices. Reduce voices or layers."
endif

if synthesis_mode = 1
    maxTriggerEstimate = number_of_voices + 2
elsif synthesis_mode = 2
    maxTriggerEstimate = 2 * number_of_voices + 3
elsif synthesis_mode = 3
    maxTriggerEstimate = max(3, floor(number_of_voices / 2) + 1)
elsif synthesis_mode = 4
    maxTriggerEstimate = 2 * number_of_voices
else
    maxTriggerEstimate = 8
endif
if duration_s * estimatedVoices * maxTriggerEstimate > 100000
    exitScript: "Settings may generate more than 100,000 strikes. Reduce duration, voices, or layers."
endif

# Object names should not consume the reproducible synthesis stream.
uid$ = string$(randomInteger(10000, 99999))
if random_seed > 0
    random_initializeWithSeedUnsafelyButPredictably (random_seed)
endif

twoPi = 2 * pi
safeTop = 0.45 * sample_rate_Hz
safeBottom = 20
nOutputSamples = round(duration_s * sample_rate_Hz)

totalVoices = 0
totalEvents = 0
antiAliasAdjustments = 0
skippedVoices = 0
minCarrierReal = 1e30
maxCarrierReal = 0
sumDecayReal = 0

# ============================================================================
# 3. Information and output canvas
# ============================================================================
writeInfoLine: "=== Algorithmic Metallic Synthesis ==="
appendInfoLine: "Preset: ", preset_name$
appendInfoLine: "Duration: ", duration_s, " s"
appendInfoLine: "Mode: ", synthesis_mode$
appendInfoLine: "Requested voices x layers: ", number_of_voices, " x ", number_of_layers
if random_seed > 0
    appendInfoLine: "Seed: ", random_seed, " (reproducible)"
else
    appendInfoLine: "Seed: 0 (unpredictable)"
endif
appendInfoLine: ""

outputSound = Create Sound from formula: "metallic_" + uid$, 1, 0, duration_s, sample_rate_Hz, "0"

# ============================================================================
# 4. Voice synthesis
#    Each voice = regular pulse train (*) exponentially decaying FM ring kernel.
#    Convolution with "sum" makes a unit pulse reproduce one kernel at unit gain.
# ============================================================================
for layer to number_of_layers
    appendInfoLine: "Layer ", layer, "/", number_of_layers, "..."

    if randomize_parameters
        layerModRate = modulation_rate_Hz * (0.7 + 0.6 * randomUniform(0, 1))
        layerDecay = resonance_decay_s * (0.8 + 0.4 * randomUniform(0, 1))
    else
        layerModRate = modulation_rate_Hz
        layerDecay = resonance_decay_s
    endif

    layerDecay = max(layerDecay, 2 / sample_rate_Hz)

    if synthesis_mode = 2
        layerVoices = number_of_voices * 2
    elsif synthesis_mode = 3
        layerVoices = max(2, floor(number_of_voices / 2))
    else
        layerVoices = number_of_voices
    endif

    for voice to layerVoices

        # --------------------------------------------------------------------
        # Voice parameters
        # --------------------------------------------------------------------
        if synthesis_mode = 1
            voiceFreq = (voice + 2) * base_frequency_Hz * (1 + (layer - 1) * 0.1)
            detune = 1 + (voice - 1) * 0.02
            voiceAmp = 0.40 / (number_of_layers * sqrt(layerVoices))
            modIndex = modulation_depth
            triggerRate = voice + 2

        elsif synthesis_mode = 2
            voiceFreq = (voice + 1) * base_frequency_Hz * (1.5 + (layer - 1) * 0.2)
            detune = 1 + (voice - 1) * 0.015
            voiceAmp = 0.30 / (number_of_layers * sqrt(layerVoices))
            modIndex = modulation_depth * 0.7
            triggerRate = voice + 3

        elsif synthesis_mode = 3
            voiceFreq = (voice + 3) * base_frequency_Hz * (0.8 + (layer - 1) * 0.3)
            detune = 1 + (voice - 1) * 0.01
            voiceAmp = 0.60 / (number_of_layers * sqrt(layerVoices))
            modIndex = modulation_depth * 1.3
            triggerRate = voice + 1

        elsif synthesis_mode = 4
            voiceFreq = voice * base_frequency_Hz * (1 + (layer - 1) * 0.15)
            detune = 1 + (voice - 1) * 0.025
            voiceAmp = 0.50 / (number_of_layers * sqrt(layerVoices))
            modIndex = modulation_depth * 0.8
            triggerRate = voice * 2

        else
            # "Chaotic Resonance" is stochastic only when Randomize_parameters
            # is enabled. With randomization OFF it becomes a fixed irregular
            # deterministic lattice, so the switch has an honest meaning.
            voiceAmp = 0.50 / (number_of_layers * sqrt(layerVoices))
            if randomize_parameters
                voiceFreq = (voice + randomUniform(0, 3)) * base_frequency_Hz * (0.7 + randomUniform(0, 0.8))
                detune = 1 + randomUniform(0, 0.05)
                modIndex = modulation_depth * (0.5 + randomUniform(0, 1))
                triggerRate = randomUniform(2, 8)
            else
                voiceFreq = (voice + 0.37 * layer) * base_frequency_Hz * (0.82 + 0.06 * layer)
                detune = 1 + 0.01 * ((voice + layer) mod 5)
                modIndex = modulation_depth * (0.70 + 0.08 * ((voice + 2 * layer) mod 5))
                triggerRate = 2 + ((2 * voice + layer) mod 7)
            endif
        endif

        if randomize_parameters and synthesis_mode <> 5
            voiceFreq = voiceFreq * (0.98 + 0.04 * randomUniform(0, 1))
            modIndex = modIndex * (0.9 + 0.2 * randomUniform(0, 1))
        endif

        carrierFreq = voiceFreq * detune
        carrierFreq = max(carrierFreq, safeBottom)

        # Approximate occupied top frequency for phase-modulated sine:
        # fc + (|beta| + 1) * fm. If needed, move fc down but preserve beta.
        sidebandMargin = (abs(modIndex) + 1) * layerModRate
        maxCarrier = safeTop - sidebandMargin
        voiceUsable = 1
        if maxCarrier <= safeBottom
            voiceUsable = 0
            skippedVoices = skippedVoices + 1
        elsif carrierFreq > maxCarrier
            carrierFreq = maxCarrier
            antiAliasAdjustments = antiAliasAdjustments + 1
        endif

        if triggerRate <= 0
            voiceUsable = 0
            skippedVoices = skippedVoices + 1
        endif

        if voiceUsable = 1
            # Realized regular strike rate on the sample grid.
            periodSamples = max(2, round(sample_rate_Hz / triggerRate))
            actualTriggerRate = sample_rate_Hz / periodSamples

            if randomize_parameters
                offsetSamples = randomInteger(0, periodSamples - 1)
            else
                offsetSamples = 0
            endif
            firstEventTime = (offsetSamples + 0.5) / sample_rate_Hz

            # Five time constants leaves < 0.7 percent of the original envelope.
            kernelDur = min(duration_s, max(0.03, 5 * layerDecay))
            modDecay = max(0.60 * layerDecay, 2 / sample_rate_Hz)

            # A faster strike rate should primarily change texture, not become
            # a hidden gain control. Compensate only where several decay
            # constants overlap on average; sparse strikes are not boosted.
            overlapFactor = max(1, actualTriggerRate * layerDecay)
            kernelAmp = voiceAmp / sqrt(overlapFactor)

            # ----------------------------------------------------------------
            # Unit pulse train on exact sample positions.
            # ----------------------------------------------------------------
            excitationSound = Create Sound from formula: "strike_" + uid$, 1, 0, duration_s, sample_rate_Hz,
                ... "if col > offsetSamples and ((col - 1 - offsetSamples) mod periodSamples = 0) then 1 else 0 fi"

            # ----------------------------------------------------------------
            # Ring kernel. The modulation index decays slightly faster than
            # amplitude, giving the classic bright-to-pure metallic evolution.
            # ----------------------------------------------------------------
            kernelSound = Create Sound from formula: "ring_" + uid$, 1, 0, kernelDur, sample_rate_Hz,
                ... "kernelAmp * exp(-x / layerDecay) * sin(twoPi * carrierFreq * x + modIndex * exp(-x / modDecay) * sin(twoPi * layerModRate * x))"

            selectObject: excitationSound
            plusObject: kernelSound
            Convolve: "sum", "zero"
            ringTrain = selected("Sound")

            # Sum only the requested output interval; convolution tails after
            # duration_s are intentionally cropped at the final output boundary.
            selectObject: outputSound
            Formula: "self + object(ringTrain, x, 1)"

            # Metadata used by the visualization: these are the ACTUAL values
            # that drove the DSP, including randomized and anti-aliased values.
            totalVoices = totalVoices + 1
            voiceCarrier[totalVoices] = carrierFreq
            voiceRate[totalVoices] = actualTriggerRate
            voiceDecay[totalVoices] = layerDecay
            voiceOffset[totalVoices] = firstEventTime
            voicePeriodSamples[totalVoices] = periodSamples
            voiceOffsetSamples[totalVoices] = offsetSamples
            voiceKernelDur[totalVoices] = kernelDur
            voiceLayer[totalVoices] = layer
            voiceAmplitude[totalVoices] = kernelAmp

            eventCount = 0
            eventCol = offsetSamples + 1
            while eventCol <= nOutputSamples
                eventCount = eventCount + 1
                eventCol = eventCol + periodSamples
            endwhile
            voiceEventCount[totalVoices] = eventCount
            totalEvents = totalEvents + eventCount

            minCarrierReal = min(minCarrierReal, carrierFreq)
            maxCarrierReal = max(maxCarrierReal, carrierFreq)
            sumDecayReal = sumDecayReal + layerDecay

            removeObject: excitationSound, kernelSound, ringTrain
        endif
    endfor
endfor

if totalVoices = 0
    if random_seed > 0
        random_initializeSafelyAndUnpredictably ()
    endif
    removeObject: outputSound
    exitScript: "No voice remained below the safe Nyquist limit. Lower the base frequency or modulation depth."
endif

meanDecayReal = sumDecayReal / totalVoices

# Restore global RNG after every stochastic DSP draw.
if random_seed > 0
    random_initializeSafelyAndUnpredictably ()
endif

appendInfoLine: ""
appendInfoLine: "Rendered voices: ", totalVoices
appendInfoLine: "Rendered strikes: ", totalEvents
appendInfoLine: "Carrier range: ", fixed$(minCarrierReal, 1), " - ", fixed$(maxCarrierReal, 1), " Hz"
appendInfoLine: "Anti-alias adjustments: ", antiAliasAdjustments
appendInfoLine: "Skipped voices: ", skippedVoices

# ============================================================================
# 5. Edge fade
# ============================================================================
if fade_time_s > 0
    selectObject: outputSound
    Formula: "if x < fade_time_s then self * (x / fade_time_s) else self fi"
    fadeOutStart = duration_s - fade_time_s
    Formula: "if x > fadeOutStart then self * ((duration_s - x) / fade_time_s) else self fi"
endif

# ============================================================================
# 6. Spatial rendering
# ============================================================================
if spatial_mode = 2
    appendInfoLine: "Spatial: Stereo Wide (short decorrelation delay)"

    wideDelay = min(0.012, max(0.003, 8 / sample_rate_Hz))

    selectObject: outputSound
    Copy: "left_" + uid$
    leftSound = selected("Sound")
    Formula: "self / sqrt(2)"

    selectObject: outputSound
    Copy: "right_" + uid$
    rightSound = selected("Sound")
    Formula: "object(outputSound, x - wideDelay, 1) / sqrt(2)"

    selectObject: leftSound
    plusObject: rightSound
    stereoSound = Combine to stereo
    Rename: "metallic_" + preset_name$

    removeObject: outputSound, leftSound, rightSound
    outputSound = stereoSound

elsif spatial_mode = 3
    appendInfoLine: "Spatial: Rotating (equal-power)"

    rotateRate = 0.3

    selectObject: outputSound
    Copy: "left_" + uid$
    leftSound = selected("Sound")
    Formula: "self * cos(0.25 * pi * (1 + sin(twoPi * rotateRate * x)))"

    selectObject: outputSound
    Copy: "right_" + uid$
    rightSound = selected("Sound")
    Formula: "self * sin(0.25 * pi * (1 + sin(twoPi * rotateRate * x)))"

    selectObject: leftSound
    plusObject: rightSound
    stereoSound = Combine to stereo
    Rename: "metallic_" + preset_name$

    removeObject: outputSound, leftSound, rightSound
    outputSound = stereoSound

else
    selectObject: outputSound
    Rename: "metallic_" + preset_name$
endif

# ============================================================================
# 7. Output level and QC
# ============================================================================
selectObject: outputSound
preNormPeak = Get absolute extremum: 0, 0, "Sinc70"

if normalize_output and preNormPeak > 0
    Scale peak: 0.9
endif

selectObject: outputSound
finalPeak = Get absolute extremum: 0, 0, "Sinc70"
finalRms = Get root-mean-square: 0, 0

appendInfoLine: "Output peak: ", fixed$(finalPeak, 4)
appendInfoLine: "Output RMS: ", fixed$(finalRms, 4)
if normalize_output = 0 and finalPeak > 0.99
    appendInfoLine: "Warning: peak exceeds 0.99 with normalization disabled; playback/export may clip."
endif

# ============================================================================
# 8. Visualization
# ============================================================================
if draw_visualization
    appendInfoLine: "Drawing mechanism / measurement visualization..."
    @drawMetallicQC: duration_s
endif

# ============================================================================
# 9. Play and final selection
# ============================================================================
if play_result
    selectObject: outputSound
    Play
endif

selectObject: outputSound
appendInfoLine: ""
appendInfoLine: "=== Done ==="
appendInfoLine: "Created: ", selected$("Sound")


# ==============================================================================
# Procedure: drawMetallicQC
# ==============================================================================
procedure drawMetallicQC: .duration

    .ink$ = "{0.18, 0.20, 0.24}"
    .blue$ = "{0.16, 0.42, 0.68}"
    .rust$ = "{0.72, 0.32, 0.20}"
    .grey$ = "{0.50, 0.52, 0.56}"
    .light$ = "{0.965, 0.968, 0.972}"
    .grid$ = "{0.84, 0.85, 0.87}"

    Erase all
    Select outer viewport: 0, 8, 0, 8
    Select inner viewport: 0, 8, 0, 8
    Axes: 0, 1, 0, 1
    Black
    Plain line
    Line width: 1

    # -------------------------------------------------------------------------
    # Header
    # -------------------------------------------------------------------------
    Select outer viewport: 0.35, 7.75, 0.08, 0.62
    Select inner viewport: 0.35, 7.75, 0.08, 0.62
    Axes: 0, 1, 0, 1
    Font size: 14
    Colour: .ink$
    Text: 0.5, "centre", 0.68, "half", "##Algorithmic Metallic Synthesis##"
    Font size: 8
    Colour: .grey$
    Text: 0.5, "centre", 0.12, "half", preset_name$ + "   |   " + synthesis_mode$ + "   |   " + string$(totalVoices) + " voices   |   " + string$(totalEvents) + " strikes"

    Select outer viewport: 0.45, 7.65, 0.67, 0.98
    Select inner viewport: 0.45, 7.65, 0.67, 0.98
    Axes: 0, 1, 0, 1
    Font size: 7
    Colour: .grey$
    Text: 0.5, "centre", 0.5, "half", "pulse train  (*)  decaying FM ring kernel   ->   overlapping metallic resonances"

    # Representative output channel: strongest channel, never a phase-cancelling
    # mono fold-down.
    selectObject: outputSound
    .nch = Get number of channels
    if .nch > 1
        Extract one channel: 1
        .ch1 = selected("Sound")
        .rms1 = Get root-mean-square: 0, 0
        selectObject: outputSound
        Extract one channel: 2
        .ch2 = selected("Sound")
        .rms2 = Get root-mean-square: 0, 0
        if .rms2 > .rms1
            .disp = .ch2
            removeObject: .ch1
        else
            .disp = .ch1
            removeObject: .ch2
        endif
    else
        selectObject: outputSound
        Copy: "metallic_display_" + uid$
        .disp = selected("Sound")
    endif

    selectObject: .disp
    .peak = Get absolute extremum: 0, 0, "Sinc70"
    .waveY = max(0.05, 1.08 * .peak)

    # -------------------------------------------------------------------------
    # Panel A: measured waveform
    # -------------------------------------------------------------------------
    Select outer viewport: 0.55, 7.65, 1.08, 1.34
    Select inner viewport: 0.55, 7.65, 1.08, 1.34
    Axes: 0, 1, 0, 1
    Font size: 9
    Colour: .ink$
    Text: 0, "left", 0.5, "half", "##A  Measured output waveform##"
    Font size: 7
    Colour: .grey$
    Text: 1, "right", 0.5, "half", "strongest channel; symmetric amplitude scale"

    Select outer viewport: 0.55, 7.65, 1.39, 2.58
    Select inner viewport: 0.82, 7.55, 1.46, 2.46
    Axes: 0, .duration, -.waveY, .waveY
    selectObject: .disp
    Colour: .blue$
    Draw: 0, .duration, -.waveY, .waveY, "no", "Curve"
    Colour: .grid$
    Draw line: 0, 0, .duration, 0
    Colour: "Black"
    Draw inner box
    Font size: 8
    Marks bottom every: 1, max(0.5, .duration / 8), "yes", "yes", "no"
    Marks left: 3, "yes", "yes", "no"
    Font size: 9
    Text bottom: "yes", "Time (s)"
    Text left: "yes", "Amplitude"

    # -------------------------------------------------------------------------
    # Panel B: actual strike / resonance map
    # -------------------------------------------------------------------------
    Select outer viewport: 0.55, 7.65, 2.79, 3.05
    Select inner viewport: 0.55, 7.65, 2.79, 3.05
    Axes: 0, 1, 0, 1
    Font size: 9
    Colour: .ink$
    Text: 0, "left", 0.5, "half", "##B  Actual strike-resonance field##"
    Font size: 7
    Colour: .grey$
    Text: 1, "right", 0.5, "half", "ticks = rendered strikes; horizontal tails = five decay constants"

    .fMinPlot = max(0, 0.88 * minCarrierReal)
    .fMaxPlot = min(safeTop, 1.08 * maxCarrierReal)
    if .fMaxPlot <= .fMinPlot
        .fMaxPlot = .fMinPlot + 100
    endif

    Select outer viewport: 0.55, 7.65, 3.10, 4.43
    Select inner viewport: 0.82, 7.55, 3.18, 4.31
    Axes: 0, .duration, .fMinPlot, .fMaxPlot

    .drawStride = max(1, ceiling(totalEvents / 900))
    .eventOrdinal = 0
    for .v to totalVoices
        .period = voicePeriodSamples[.v] / sample_rate_Hz
        .tt = voiceOffset[.v]
        .f = voiceCarrier[.v]
        .tail = voiceKernelDur[.v]
        while .tt < .duration
            .eventOrdinal = .eventOrdinal + 1
            if .eventOrdinal - floor(.eventOrdinal / .drawStride) * .drawStride = 0 or .drawStride = 1
                .endTail = min(.duration, .tt + .tail)
                Colour: "{0.76, 0.82, 0.88}"
                Line width: 0.5
                Draw line: .tt, .f, .endTail, .f
                Colour: .rust$
                Line width: 1
                .tick = max(3, 0.012 * (.fMaxPlot - .fMinPlot))
                Draw line: .tt, max(.fMinPlot, .f - .tick), .tt, min(.fMaxPlot, .f + .tick)
            endif
            .tt = .tt + .period
        endwhile
    endfor

    Colour: "Black"
    Line width: 1
    Draw inner box
    Font size: 8
    Marks bottom every: 1, max(0.5, .duration / 8), "yes", "yes", "no"
    Marks left: 5, "yes", "yes", "no"
    Font size: 9
    Text bottom: "yes", "Time (s)"
    Text left: "yes", "Carrier (Hz)"

    # -------------------------------------------------------------------------
    # Panel C: measured spectrum over time + model carriers
    # -------------------------------------------------------------------------
    Select outer viewport: 0.55, 7.65, 4.66, 4.92
    Select inner viewport: 0.55, 7.65, 4.66, 4.92
    Axes: 0, 1, 0, 1
    Font size: 9
    Colour: .ink$
    Text: 0, "left", 0.5, "half", "##C  Model -> measurement##"
    Font size: 7
    Colour: .grey$
    Text: 1, "right", 0.5, "half", "measured spectrogram with actual carrier-frequency guides"

    .specTop = min(safeTop, max(2000, 1.15 * maxCarrierReal))
    selectObject: .disp
    To Spectrogram: 0.025, .specTop, 0.005, 20, "Gaussian"
    .spec = selected("Spectrogram")

    Select outer viewport: 0.55, 7.65, 4.97, 6.42
    Select inner viewport: 0.82, 7.55, 5.05, 6.30
    selectObject: .spec
    Paint: 0, .duration, 0, .specTop, 100, "no", 50, 6, 0, "no"

    Select inner viewport: 0.82, 7.55, 5.05, 6.30
    Axes: 0, .duration, 0, .specTop

    .guideStride = max(1, ceiling(totalVoices / 24))
    Colour: "{0.92, 0.68, 0.30}"
    Line width: 0.7
    for .v to totalVoices
        if .v - floor(.v / .guideStride) * .guideStride = 0 or .guideStride = 1
            Draw line: 0, voiceCarrier[.v], .duration, voiceCarrier[.v]
        endif
    endfor

    Colour: "Black"
    Line width: 1
    Draw inner box
    Font size: 8
    Marks bottom every: 1, max(0.5, .duration / 8), "yes", "yes", "no"
    Marks left: 5, "yes", "yes", "no"
    Font size: 9
    Text bottom: "yes", "Time (s)"
    Text left: "yes", "Frequency (Hz)"

    removeObject: .spec
    removeObject: .disp

    # -------------------------------------------------------------------------
    # Mechanism strip
    # -------------------------------------------------------------------------
    Select outer viewport: 0.55, 7.65, 6.62, 7.05
    Select inner viewport: 0.55, 7.65, 6.62, 7.05
    Axes: 0, 1, 0, 1
    Paint rectangle: .light$, 0, 1, 0, 1
    Colour: .ink$
    Draw inner box
    Font size: 8
    Text: 0.5, "centre", 0.66, "half", "strike train  (*)  h(t) = exp(-t/tau) sin(2*pi*fc*t + beta exp(-t/tauM) sin(2*pi*fm*t))"
    Font size: 7
    Colour: .grey$
    Text: 0.5, "centre", 0.25, "half", "convolution preserves overlapping ring tails; tau = Resonance decay"

    # -------------------------------------------------------------------------
    # Summary dashboard
    # -------------------------------------------------------------------------
    if spatial_mode = 2
        .spatial$ = "Stereo Wide"
    elsif spatial_mode = 3
        .spatial$ = "Rotating"
    else
        .spatial$ = "Mono"
    endif

    Select outer viewport: 0.55, 7.65, 7.18, 7.86
    Select inner viewport: 0.55, 7.65, 7.18, 7.86
    Axes: 0, 1, 0, 1
    Paint rectangle: "{0.94, 0.94, 0.94}", 0, 1, 0, 1
    Colour: "Black"
    Draw inner box

    Font size: 7
    Colour: .grey$
    Text: 0.02, "left", 0.72, "half", "MODEL"
    Colour: .ink$
    Text: 0.02, "left", 0.34, "half", fixed$(minCarrierReal, 0) + "-" + fixed$(maxCarrierReal, 0) + " Hz   |   mean tau " + fixed$(meanDecayReal, 3) + " s   |   " + string$(totalEvents) + " strikes"

    Colour: .grey$
    Text: 0.50, "centre", 0.72, "half", "VALIDATION"
    Colour: .ink$
    Text: 0.50, "centre", 0.34, "half", "AA adjusted " + string$(antiAliasAdjustments) + "   |   skipped " + string$(skippedVoices) + "   |   peak " + fixed$(finalPeak, 3)

    Colour: .grey$
    Text: 0.98, "right", 0.72, "half", "OUTPUT"
    Colour: .ink$
    if random_seed > 0
        .seed$ = string$(random_seed)
    else
        .seed$ = "random"
    endif
    Text: 0.98, "right", 0.34, "half", .spatial$ + "   |   RMS " + fixed$(finalRms, 3) + "   |   seed " + .seed$

    Font size: 10
    Colour: "Black"
    Line width: 1
endproc
